import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import vm from "node:vm";

const engine=readFileSync("crm/js/assistant-engine.js","utf8"),migration=readFileSync("supabase/migrations/20260915010000_assistant_commercial_intelligence.sql","utf8"),hardening=readFileSync("supabase/migrations/20260915030000_assistant_entitlement_hardening.sql","utf8"),premium=readFileSync("crm/js/premium.js","utf8"),data=readFileSync("crm/js/premium-data.js","utf8"),insights=readFileSync("crm/js/lead-insights.js","utf8");
const normalizeText=value=>String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();
const context=vm.createContext({Date,Intl,Number,String,Math,Array,Object,Map,Set,normalizeText,normalizePhone:v=>String(v||"").replace(/\D/g,"").replace(/^55(?=\d{10,11}$)/,""),formatPhone:v=>`(${String(v).slice(0,2)}) ${String(v).slice(2,7)}-${String(v).slice(7)}`,parseBrlNumber:value=>{const raw=String(value||"").replace(/[^\d,.]/g,"");return Number(raw.replace(/\.(?=\d{3}(?:\D|$))/g,"").replace(",","."));},activityKindLabel:k=>({visita:"Visita",retorno:"Follow-up",tarefa:"Tarefa"}[k]||k),stageLabel:v=>v,leadNextBestAction:()=>({action:"Retomar contato",reason:"Sem atividade",weight:50}),matchProperties:()=>[],buildDemandRadar:()=>[],isOpenProposal:p=>["draft","sent","negotiating"].includes(p.status),formatPrice:v=>`R$ ${v}`});
vm.runInContext(engine,context);

test("AI01 natural activity command creates preview only",()=>{const parsed=context.parseAssistantCommand("Agende uma visita com João amanhã às 15h",{leads:[{id:"l1",name:"João"}],now:new Date("2026-09-15T10:00:00-04:00")});assert.equal(parsed.kind,"create_activity");assert.equal(parsed.mutating,true);assert.equal(parsed.payload.lead_id,"l1");assert.match(parsed.payload.scheduled_at,/T19:00:00\.000Z$/);});
test("AI02 destructive and entitlement commands are rejected",()=>assert.equal(context.parseAssistantCommand("mude meu plano e entitlement",{}).kind,"blocked"));
test("AI03 proposals require lead and a valid numeric value",()=>{const p=context.parseAssistantCommand("Crie uma proposta de R$ 500.000 para João",{leads:[{id:"l1",name:"João"}],now:new Date("2026-09-15T10:00:00Z")});assert.equal(p.kind,"create_proposal");assert.equal(p.payload.proposed_price,500000);});
test("AI04 message drafts use selected facts and never send",()=>{const message=context.assistantMessageTemplate("property",{lead:{name:"João Silva"},property:{codigo:"VCI000006",titulo:"Apartamento"}});assert.match(message,/João/);assert.match(message,/VCI000006/);assert.doesNotMatch(engine,/fetch\(|supabaseRequest\(/);});
test("AI05 ad drafts contain only supplied property facts",()=>{const draft=context.buildPropertyAdDraft({codigo:"VCI1",titulo:"Casa",preco:500000,quartos:2,caracteristicas:["Piscina"]});assert.match(draft.whatsapp,/500000/);assert.deepEqual([...draft.highlights],["Piscina"]);assert.doesNotMatch(draft.summary,/suíte|vaga/i);});
test("AI06 deterministic lead summary reports real activity and proposals",()=>{const summary=context.buildLeadCommercialSummary({id:"l1",name:"Maria",stage:"novo"},{activities:[{lead_id:"l1",kind:"visita",scheduled_at:"2026-09-15"}],proposals:[{lead_id:"l1",status:"sent"}],memory:[{memory_kind:"objection",content:"Preço"}]});assert.equal(summary.visits,1);assert.equal(summary.openProposals,1);assert.deepEqual([...summary.objections],["Preço"]);});
test("AI07 financial pipeline distinguishes expected, received and pending",()=>{const result=context.buildFinancialPipeline([{status:"accepted",final_price:500000,commission_expected:25000,commission_received:10000,proposal_date:"2026-09-10"}],new Date("2026-09-15"));assert.equal(result.vgv,500000);assert.equal(result.pendingCommission,15000);assert.equal(result.monthlyForecast,25000);});
test("AI08 backend previews are expiring, rate limited and entitlement gated",()=>{assert.match(migration,/expires_at timestamptz[^\n]+15 minutes/);assert.match(migration,/count\(\*\)[\s\S]+10/);assert.match(migration,/can_use_entitlement\(target_organization,'crm\.assistant'\)/);});
test("AI09 confirmation is server-side, audited and derives actor",()=>{assert.match(migration,/confirm_assistant_action/);assert.match(migration,/auth\.uid\(\)/);assert.match(migration,/assistant_action_confirmed/);assert.doesNotMatch(migration,/service_role/);});
test("AI10 memory and summaries are tenant scoped by lead access",()=>{assert.match(migration,/lead_memory_select[\s\S]+can_access_lead/);assert.match(migration,/get_lead_commercial_summary[\s\S]+can_access_lead/);assert.match(migration,/force row level security/);});
test("AI11 frontend requires preview then explicit confirmation",()=>{assert.match(premium,/Preparar ação/);assert.match(premium,/Confirmar e salvar/);assert.match(data,/prepare_assistant_action/);assert.match(data,/confirm_assistant_action/);});
test("AI12 no provider or generative claim is fabricated",()=>{const all=[engine,premium,data,migration].join("\n");assert.doesNotMatch(all,/OPENAI_API_KEY|ANTHROPIC_API_KEY|service_role/);assert.match(premium,/Templates determinísticos/);});
test("AI13 natural lead command requires valid name and phone before preview",()=>{const parsed=context.parseAssistantCommand("Crie um lead João Silva com telefone (65) 99999-1111",{});assert.equal(parsed.kind,"create_lead");assert.equal(parsed.payload.name,"João Silva");assert.equal(parsed.payload.phone,"65999991111");assert.equal(parsed.mutating,true);});
test("AI14 property ads are exposed as factual deterministic drafts",()=>{assert.match(premium,/Anúncio assistido/);assert.match(premium,/buildPropertyAdDraft/);assert.match(premium,/somente informações cadastradas/);});
test("AI15 commercial memory is entitlement-gated in database and UI",()=>{assert.match(hardening,/can_use_entitlement\(organization_id,'crm\.assistant'\)/);assert.match(insights,/hasEntitlement\("crm\.assistant"\)/);});
