function activityDateInput(value) { const date=value?new Date(value):new Date(Date.now()+3600000),pad=n=>String(n).padStart(2,"0"); return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function activityStatusLabel(status){return({agendado:"Agendado",concluido:"Concluído",cancelado:"Cancelado"})[status]||status;}
function activityKindLabel(kind){return({retorno:"Follow-up",visita:"Visita",tarefa:"Tarefa",reuniao:"Reunião"})[kind]||kind;}

async function openActivityModal({activity=null,lead=null,leads=null,onSaved=null}={}) {
  const [availableLeads,membership]=await Promise.all([leads||getLeads(),getActiveMembership()]);
  const canAssign=["owner","manager"].includes(membership.role),members=canAssign?await getKanbanMembers():[];
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"activityTitle"}}); card.append(createElement("h2",{attrs:{id:"activityTitle"},text:activity?"Reagendar atividade":"Nova atividade"}));
  const form=createElement("form",{className:"crm-form"}); function field(text,control){const label=createElement("label",{text});label.append(control);form.append(label);return control;}
  const leadSelect=field("Lead",createElement("select",{attrs:{required:""}}));leadSelect.append(new Option("Selecione",""));availableLeads.forEach(item=>leadSelect.append(new Option(item.name,item.id)));leadSelect.value=activity?.lead_id||lead?.id||"";
  const title=field("Atividade",createElement("input",{type:"text",attrs:{required:"",maxlength:"160",placeholder:"Ex.: Ligar após aprovação bancária"}}));title.value=activity?.title||"";
  const grid=createElement("div",{className:"form-grid"});form.append(grid);const kindLabel=createElement("label",{text:"Tipo"}),kind=createElement("select");[["retorno","Follow-up"],["visita","Visita"],["tarefa","Tarefa"],["reuniao","Reunião"]].forEach(([value,text])=>kind.append(new Option(text,value)));kind.value=activity?.kind||"retorno";kindLabel.append(kind);
  const dateLabel=createElement("label",{text:"Data e horário"}),scheduled=createElement("input",{type:"datetime-local",attrs:{required:""}});scheduled.value=activityDateInput(activity?.scheduled_at);dateLabel.append(scheduled);grid.append(kindLabel,dateLabel);
  const priority=field("Prioridade",createElement("select"));[[1,"Alta"],[2,"Normal"],[3,"Baixa"]].forEach(([value,text])=>priority.append(new Option(text,value)));priority.value=activity?.priority||2;
  const assignee=field("Responsável",createElement("select"));if(canAssign){assignee.append(new Option("Sem responsável",""));members.filter(item=>item.status==="active").forEach(item=>assignee.append(new Option(item.full_name||"Membro",item.user_id)));assignee.value=activity?.assigned_to||lead?.assigned_to||"";}else{const user=getStoredSession()?.user?.id||"demo-owner";assignee.append(new Option("Você",user));assignee.value=user;assignee.disabled=true;}
  const notes=field("Observação",createElement("textarea",{attrs:{maxlength:"5000"}}));notes.value=activity?.notes||"";const error=createElement("p",{className:"form-error",attrs:{role:"alert"}});form.append(error);
  const actions=createElement("div",{className:"modal-actions"}),cancel=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Cancelar"}),save=createElement("button",{type:"submit",className:"crm-button crm-button-primary",text:"Salvar atividade"});cancel.addEventListener("click",closeModal);actions.append(cancel,save);form.append(actions);
  form.addEventListener("submit",async event=>{event.preventDefault();if(save.disabled)return;save.disabled=true;error.textContent="";try{await saveCrmActivity({id:activity?.id,lead_id:leadSelect.value,assigned_to:assignee.value,kind:kind.value,title:title.value,scheduled_at:new Date(scheduled.value).toISOString(),priority:priority.value,notes:notes.value});closeModal();showToast(activity?"Atividade reagendada.":"Atividade criada.");await onSaved?.();}catch(reason){error.textContent=reason.message||"Não foi possível salvar a atividade.";}finally{save.disabled=false;}});
  card.append(form);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");title.focus();
}

function createActivityCard(activity,leads,refresh){const lead=leads.find(item=>item.id===activity.lead_id),card=createElement("article",{className:`agenda-item activity-priority-${activity.priority}`});card.append(createElement("div",{className:"agenda-date",text:formatDate(activity.scheduled_at,true)}));const body=createElement("div");body.append(createElement("strong",{text:activity.title}),createElement("span",{text:`${lead?.name||"Lead indisponível"} · ${activityKindLabel(activity.kind)}`}),createElement("span",{className:`stage stage-${activity.status}`,text:activityStatusLabel(activity.status)}));card.append(body);if(activity.status==="agendado"){const menu=createElement("div",{className:"activity-actions"}),complete=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Concluir"}),reschedule=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Reagendar"}),cancel=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Cancelar"});complete.addEventListener("click",async()=>{try{await setCrmActivityStatus(activity.id,"concluido");showToast("Atividade concluída.");await refresh();}catch(error){showToast(error.message,"error");}});cancel.addEventListener("click",async()=>{try{await setCrmActivityStatus(activity.id,"cancelado");showToast("Atividade cancelada.");await refresh();}catch(error){showToast(error.message,"error");}});reschedule.addEventListener("click",()=>openActivityModal({activity,leads,onSaved:refresh}));menu.append(complete,reschedule,cancel);card.append(menu);}return card;}

async function renderAgenda(root){const [leads,activities]=await Promise.all([getLeads(),getCrmActivities()]);if(!root.isConnected)return;root.replaceChildren();const toolbar=createElement("div",{className:"toolbar"}),filter=createElement("select",{className:"filter-select",attrs:{"aria-label":"Filtrar agenda"}});[["active","Abertas"],["today","Hoje"],["overdue","Atrasadas"],["completed","Concluídas"],["all","Todas"]].forEach(([value,text])=>filter.append(new Option(text,value)));const create=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"+ Nova atividade"});create.addEventListener("click",()=>openActivityModal({leads,onSaved:()=>renderAgenda(root)}));toolbar.append(filter,create);root.append(toolbar);const list=createElement("section",{className:"agenda-list advanced-agenda"});root.append(list);function draw(){const now=new Date(),start=startOfToday(),end=new Date(start.getTime()+86400000);let shown=activities;if(filter.value==="active")shown=shown.filter(item=>item.status==="agendado");if(filter.value==="today")shown=shown.filter(item=>item.status==="agendado"&&new Date(item.scheduled_at)>=start&&new Date(item.scheduled_at)<end);if(filter.value==="overdue")shown=shown.filter(item=>item.status==="agendado"&&new Date(item.scheduled_at)<now);if(filter.value==="completed")shown=shown.filter(item=>item.status==="concluido");list.replaceChildren();if(!shown.length)list.append(createEmptyState("Nenhuma atividade","Crie um follow-up para manter o relacionamento em dia."));else shown.forEach(item=>list.append(createActivityCard(item,leads,()=>renderAgenda(root))));}filter.addEventListener("change",draw);draw();}
