const BILLING_STATUS_LABELS = { trialing: "Período de teste", active: "Ativa", past_due: "Pagamento pendente", grace_period: "Período de tolerância", canceled: "Cancelada", expired: "Expirada" };
function billingDate(value) { return value ? formatDate(value, true) : "Sem data definida"; }
function billingMoney(cents, currency) { return new Intl.NumberFormat("pt-BR", { style: "currency", currency: currency || "BRL" }).format((cents || 0) / 100); }
async function renderBilling(root) {
  const membership = await getActiveMembership();
  if (!["owner", "manager"].includes(membership.role)) { root.replaceChildren(createEmptyState("Acesso restrito", "Somente proprietários e gerentes podem consultar o plano.")); return; }
  const { subscription, entitlements, plans } = await getBillingOverview();
  if (!subscription) { root.replaceChildren(createEmptyState("Assinatura indisponível", "Não encontramos uma assinatura atual para esta organização.")); return; }
  root.replaceChildren(); const summary = createElement("section", { className: "billing-summary" }); const main = createElement("article", { className: "crm-panel" });
  main.append(createElement("span", { className: subscription.is_entitled ? "billing-status" : "billing-status is-danger", text: BILLING_STATUS_LABELS[subscription.status] || subscription.status }), createElement("h2", { text: `Plano ${subscription.plan_name}` }));
  main.append(createElement("p", { className: "muted", text: subscription.status === "trialing" ? `Teste disponível até ${billingDate(subscription.trial_ends_at)}.` : `Período atual até ${billingDate(subscription.current_period_ends_at)}.` }));
  if (subscription.cancel_at_period_end) main.append(createElement("p", { className: "billing-status is-warning", text: "Cancelamento programado para o fim do período" }));
  if (subscription.pending_plan_code) main.append(createElement("p", { className: "muted", text: `Mudança para ${subscription.pending_plan_code.toUpperCase()} em ${billingDate(subscription.plan_change_effective_at)}.` }));
  const seats = entitlements.find(item => item.entitlement_key === "team.members"); const usage = createElement("article", { className: "crm-panel" }); usage.append(createElement("h2", { text: "Uso da equipe" }), createElement("strong", { className: "plan-price", text: `${seats?.used_value || 0} / ${seats?.limit_value ?? "∞"}` }), createElement("p", { className: "muted", text: "Membros ativos e desativados ocupam vagas. Convites pendentes também são considerados ao convidar." })); summary.append(main, usage); root.append(summary);
  const grid = createElement("section", { className: "plan-grid", attrs: { "aria-label": "Planos disponíveis" } });
  plans.forEach(plan => { const card = createElement("article", { className: `plan-card${plan.plan_code === subscription.plan_code ? " is-current" : ""}` }); card.append(createElement("h2", { text: plan.plan_name }), createElement("p", { className: "plan-price", text: `${billingMoney(plan.monthly_price_cents, plan.currency)}/mês` }), createElement("p", { className: "muted", text: `${plan.trial_days} dia(s) de teste configurado(s)` })); const list = document.createElement("ul"); list.append(createElement("li", { text: `${plan.team_member_limit ?? "Ilimitadas"} vaga(s) de equipe` }), createElement("li", { text: "Seus dados são preservados em mudanças de plano" })); card.append(list); card.append(plan.plan_code === subscription.plan_code ? createElement("span", { className: "billing-status", text: "Plano atual" }) : createElement("p", { className: "muted", text: "Mudanças são processadas pelo canal comercial; nenhuma cobrança é iniciada nesta tela." })); grid.append(card); }); root.append(grid);
}
