const DOCUMENT_TYPE_LABELS={sale_intermediation:"Autorização / Intermediação de venda",property_sale_purchase:"Contrato particular de compra e venda"};
const DOCUMENT_STATUS_LABELS={draft:"Rascunho",review:"Em revisão",finalized:"Finalizado",canceled:"Cancelado"};
let pendingDocumentReferenceFilter=null;
function openDocumentsForReference(kind,id,label){pendingDocumentReferenceFilter={kind,id,label};closeModal();navigateCrm("documents");}
const DOCUMENT_FIELDS={
  sale_intermediation:[
    ["seller_name","Proprietário / contratante","text",true],["seller_contact","Contato do proprietário","text",false],["broker_name","Corretor / contratado","text",true],["broker_creci","CRECI","text",true],["broker_contact","Contato do corretor","text",false],
    ["property_description","Identificação completa do imóvel","textarea",true],["registry_information","Matrícula / registro (somente se cadastrado)","text",false],["offer_price","Preço pretendido","currency",true],["commercial_conditions","Condições comerciais","textarea",true],["remuneration_terms","Remuneração / corretagem acordada","textarea",true],["term_text","Prazo da intermediação","text",true],
    ["exclusivity","Modalidade","select",true,{exclusive:"EXCLUSIVA",non_exclusive:"NÃO EXCLUSIVA"}],["publicity_authorization","Canais e limites autorizados para divulgação","textarea",true],["closing_terms","Condições de encerramento","textarea",true],["city","Local","text",true],["document_date","Data","date",true]
  ],
  property_sale_purchase:[
    ["seller_name","Vendedor(es)","text",true],["seller_contact","Contato do(s) vendedor(es)","text",false],["buyer_name","Comprador(es)","text",true],["buyer_contact","Contato do(s) comprador(es)","text",false],["property_description","Identificação completa do imóvel","textarea",true],["registry_information","Matrícula / registro (somente se cadastrado)","text",false],
    ["price","Preço","currency",true],["payment_terms","Forma de pagamento e parcelas","textarea",true],["arras_option","Haverá sinal / arras?","select",true,{none:"Não",applicable:"Sim - informar condições"}],["arras_terms","Condições do sinal / arras","textarea",false],["financing_option","Haverá financiamento?","select",true,{none:"Não",applicable:"Sim - informar condições"}],["financing_terms","Condições do financiamento","textarea",false],
    ["possession_terms","Condições e data da posse","textarea",true],["deed_transfer_terms","Escritura e transferência","textarea",true],["taxes_expenses_terms","Tributos e despesas","textarea",true],["debts_terms","Débitos existentes ou declaração correspondente","textarea",true],["brokerage_terms","Corretagem","textarea",true],["default_terms","Condições de inadimplemento","textarea",true],["termination_terms","Condições de rescisão","textarea",true],["city","Local","text",true],["document_date","Data","date",true],["witnesses","Testemunhas (opcional)","textarea",false]
  ]
};

async function loadDocumentWorkspace(){
  const org=await getActiveOrganizationId();
  const [templates,documents,versions,properties,owners,leads,proposals,organizations]=await Promise.all([
    supabaseRequest("/rest/v1/document_templates?status=in.(active,legal_review_required)&select=*&order=template_code,version.desc"),
    supabaseRequest(`/rest/v1/real_estate_documents?organization_id=eq.${encodeURIComponent(org)}&select=*&order=updated_at.desc`),
    supabaseRequest(`/rest/v1/real_estate_document_versions?organization_id=eq.${encodeURIComponent(org)}&select=*&order=version_no.desc`),
    loadProperties(),
    supabaseRequest(`/rest/v1/property_owners?organization_id=eq.${encodeURIComponent(org)}&select=id,full_name,phone,email,assigned_to,status&order=full_name`),
    getLeads(),getProposals().catch(()=>[]),supabaseRequest(`/rest/v1/organizations?id=eq.${encodeURIComponent(org)}&select=id,name,trade_name,public_phone,public_whatsapp,creci,commercial_signature,current_document_identity_id`)
  ]);
  const organization=organizations[0]||{},identity=organization.current_document_identity_id?await loadDocumentIdentity(org,organization.current_document_identity_id):null;
  return{org,templates,documents,versions,properties,owners,leads,proposals,organization,identity};
}
async function loadDocumentIdentity(organizationId,identityId){if(!identityId)return null;const rows=await supabaseRequest(`/rest/v1/organization_document_identities?id=eq.${encodeURIComponent(identityId)}&organization_id=eq.${encodeURIComponent(organizationId)}&select=id,version_no,logo_bytes,logo_mime_type,logo_width,logo_height,logo_sha256,created_at`);return rows[0]||null;}
function documentIdentitySnapshot(snapshot={},organization={}){return{organization_name:snapshot.organization_name||organization.name||null,trade_name:snapshot.trade_name||organization.trade_name||null,public_phone:snapshot.public_phone||organization.public_phone||null,public_whatsapp:snapshot.public_whatsapp||organization.public_whatsapp||null,creci:snapshot.creci||organization.creci||null,commercial_signature:snapshot.commercial_signature||organization.commercial_signature||null,...snapshot};}
async function documentPdfLogo(identity){if(!identity?.logo_bytes)return null;return prepareDocumentLogoForPdf({bytes:documentLogoBytes(identity.logo_bytes),mime:identity.logo_mime_type,width:identity.logo_width,height:identity.logo_height});}
function documentPropertyId(item){return item?._row?.id||item?.id||null;}
function appendSelectOptions(select,items,valueOf,labelOf,emptyLabel){select.replaceChildren(new Option(emptyLabel||"Não vincular",""));items.forEach(item=>select.append(new Option(labelOf(item),valueOf(item))));}
function createDocumentReferenceSelect(labelText,items,valueOf,labelOf,selected="") {const label=createElement("label",{text:labelText}),select=createElement("select");appendSelectOptions(select,items,valueOf,labelOf,"Não vincular");select.value=selected||"";label.append(select);return{label,select};}
function createDocumentInput(definition,value=""){
  const[key,labelText,kind,required,options]=definition,label=createElement("label",{text:`${labelText}${required?" *":""}`}),input=kind==="textarea"?createElement("textarea",{attrs:{rows:"3",maxlength:"5000"}}):kind==="select"?createElement("select"):createElement("input",{type:kind==="date"?"date":"text",attrs:{maxlength:"5000"}});
  input.name=key;if(required)input.required=true;
  if(kind==="select"){input.append(new Option("Selecione",""));Object.entries(options).forEach(([optionValue,optionLabel])=>input.append(new Option(optionLabel,optionValue)));}
  input.value=value==null?"":String(value);if(kind==="currency")bindCurrencyInput(input);label.append(input);return{label,input,key};
}
function documentMissingLabel(key,type){return DOCUMENT_FIELDS[type]?.find(field=>field[0]===key)?.[1]||key;}
function documentSafeFilename(document,version){return `vc-imob-${document.document_type}-${document.id.slice(0,8)}-v${version.version_no}.pdf`;}

async function renderDocuments(root){
  if(!await hasEntitlement("crm.documents")){root.replaceChildren(createFeatureNotice("Documentos","Disponível nos planos PRO e EQUIPE."));return;}
  if(isDemoMode()){root.replaceChildren(createEmptyState("Documentos indisponíveis na demonstração","Este módulo exige uma organização autenticada para preservar dados privados e versões."));return;}
  const workspace=await loadDocumentWorkspace();if(!root.isConnected)return;root.replaceChildren();
  const toolbar=createElement("div",{className:"toolbar document-toolbar"}),create=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"+ Novo documento"});
  create.addEventListener("click",async()=>{if(create.disabled)return;create.disabled=true;try{await openDocumentEditor(workspace);}catch(error){console.error("Document editor failed",{operation:"open_document_editor",code:error?.code||"unexpected_error"});showToast(crmFriendlyError(error,"Não foi possível abrir o novo documento. Tente novamente."),"error");}finally{create.disabled=false;}});const activeDocuments=pendingDocumentReferenceFilter?workspace.documents.filter(item=>item[`${pendingDocumentReferenceFilter.kind}_id`]===pendingDocumentReferenceFilter.id):workspace.documents;const caption=createElement("p",{className:"muted",text:pendingDocumentReferenceFilter?`Histórico relacionado a ${pendingDocumentReferenceFilter.label}`:`${workspace.documents.length} documento(s) no histórico`});toolbar.append(caption);if(pendingDocumentReferenceFilter){const clear=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Ver todos"});clear.addEventListener("click",()=>{pendingDocumentReferenceFilter=null;renderCurrentView();});toolbar.append(clear);}toolbar.append(create);root.append(toolbar);
  const notice=createElement("section",{className:"crm-panel document-legal-notice"});notice.append(createElement("strong",{text:"Modelos controlados e versionados"}),createElement("p",{text:"O módulo reaproveita dados do CRM, exige preview e não substitui revisão jurídica profissional. Não há assinatura eletrônica nesta etapa."}));root.append(notice);
  const list=createElement("section",{className:"document-list"});
  if(!activeDocuments.length)list.append(createEmptyState("Nenhum documento encontrado","Crie um rascunho, revise todos os campos e visualize o conteúdo antes de finalizar."));
  activeDocuments.forEach(document=>{
    const version=workspace.versions.find(item=>item.document_id===document.id&&item.version_no===document.current_version),property=workspace.properties.find(item=>documentPropertyId(item)===document.property_id),owner=workspace.owners.find(item=>item.id===document.owner_id),lead=workspace.leads.find(item=>item.id===document.lead_id),card=createElement("article",{className:"crm-panel document-card"});
    const heading=createElement("div",{className:"document-card-heading"});heading.append(createElement("div",{className:"min-width-zero"}),createElement("span",{className:`stage document-status-${document.status}`,text:DOCUMENT_STATUS_LABELS[document.status]||document.status}));heading.firstChild.append(createElement("h2",{text:DOCUMENT_TYPE_LABELS[document.document_type]}),createElement("p",{className:"muted",text:`Versão ${document.current_version} · ${formatDate(document.updated_at,true)}`}));card.append(heading);
    card.append(createElement("p",{text:[property?.codigo,owner?.full_name,lead?.name].filter(Boolean).join(" · ")||"Sem vínculo complementar"}));
    const actions=createElement("div",{className:"property-admin-actions document-actions"}),open=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Abrir histórico"});open.addEventListener("click",()=>openDocumentHistory(workspace,document));actions.append(open);
    if(document.status!=="canceled"){const edit=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:document.status==="finalized"?"Criar nova versão":"Revisar / editar"});edit.addEventListener("click",()=>openDocumentEditor(workspace,document,version));actions.append(edit);}
    if(version?.status==="finalized"){const pdf=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"Gerar PDF"});pdf.addEventListener("click",()=>generateDocumentPdf(document,version));actions.append(pdf);}
    if(document.status!=="canceled"){const cancel=createElement("button",{type:"button",className:"crm-button crm-button-danger",text:"Cancelar documento"});cancel.addEventListener("click",()=>openDestructiveConfirmation({title:"Cancelar documento?",message:"O histórico e as versões serão preservados. Esta ação não apaga o conteúdo auditável.",confirmLabel:"Cancelar documento",busyLabel:"Cancelando…",successMessage:"Documento cancelado.",fallbackError:"Não foi possível cancelar o documento.",onConfirm:async()=>{await callCrmRpc("cancel_real_estate_document",{target_organization:workspace.org,target_document:document.id});await renderCurrentView();}}));actions.append(cancel);}
    card.append(actions);list.append(card);
  });root.append(list);
}

async function generateDocumentPdf(document,version){
  try{const organizationId=await getActiveOrganizationId(),identity=await loadDocumentIdentity(organizationId,version.document_identity_id),logo=await documentPdfLogo(identity),organization=(await supabaseRequest(`/rest/v1/organizations?id=eq.${encodeURIComponent(organizationId)}&select=id,name,trade_name,public_phone,public_whatsapp,creci,commercial_signature`))[0]||{};await callCrmRpc("record_real_estate_document_pdf",{target_organization:organizationId,target_document:document.id,target_version:version.version_no});downloadRealEstateDocumentPdf({title:DOCUMENT_TYPE_LABELS[document.document_type],content:version.rendered_content,identity:documentIdentitySnapshot(version.identity_snapshot,organization),logo,versionLabel:`Documento v${version.version_no} · Modelo ${version.template_code} v${version.template_version}`,generatedAt:new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date()),filename:documentSafeFilename(document,version)});showToast("PDF gerado no dispositivo.");}catch(error){console.error("Document PDF failed",{operation:"generate_document_pdf",code:error?.code||"invalid_logo_or_pdf"});showToast(crmFriendlyError(error,"Não foi possível gerar o PDF. Verifique a identidade documental e tente novamente."),"error");}
}

function createDocumentPreviewPages({title,content,identity,logo,logoDataUrl,versionLabel}){const host=createElement("div",{className:"document-preview-pages"}),pages=layoutRealEstateDocumentPdf({title,content,identity,logo});pages.forEach((page,index)=>{const sheet=createElement("section",{className:"document-preview-page",attrs:{"aria-label":`Página ${index+1} de ${pages.length}`}});if(index===0&&logoDataUrl)sheet.append(createElement("img",{attrs:{src:logoDataUrl,alt:`Logo de ${identity.trade_name||identity.organization_name||"organização"}`}}));else if(index===0)sheet.append(createElement("strong",{text:identity.trade_name||identity.organization_name||"Documento imobiliário"}));if(index===0)sheet.append(createElement("h3",{text:title}));page.elements.forEach(item=>sheet.append(createElement("p",{className:item.font==="bold"?"document-preview-heading":"",text:item.text})));const footer=createElement("footer");footer.append(createElement("span",{text:versionLabel}),createElement("span",{text:`Página ${index+1} de ${pages.length}`}));sheet.append(footer);host.append(sheet);});return host;}

function openDocumentHistory(workspace,documentRecord){
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-history-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"documentHistoryTitle"}});card.append(createElement("h2",{id:"documentHistoryTitle",text:"Histórico do documento"}),createElement("p",{className:"muted",text:`${DOCUMENT_TYPE_LABELS[documentRecord.document_type]} · ${DOCUMENT_STATUS_LABELS[documentRecord.status]}`}));
  workspace.versions.filter(item=>item.document_id===documentRecord.id).sort((a,b)=>b.version_no-a.version_no).forEach(version=>{const row=createElement("article",{className:"document-version-row"}),summary=createElement("div",{className:"min-width-zero"});summary.append(createElement("strong",{text:`Versão ${version.version_no}`}),createElement("span",{text:`${DOCUMENT_STATUS_LABELS[version.status]} · modelo v${version.template_version} · ${formatDate(version.created_at,true)}`}),createElement("small",{text:version.changes_summary||"Sem resumo de alterações."}));const preview=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Visualizar"});preview.addEventListener("click",async()=>{preview.disabled=true;try{await openFinalContent(version,documentRecord.document_type);}catch(error){showToast(crmFriendlyError(error,"Não foi possível abrir esta versão."),"error");}finally{preview.disabled=false;}});row.append(summary,preview);if(version.status==="finalized"){const pdf=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"PDF"});pdf.addEventListener("click",()=>generateDocumentPdf(documentRecord,version));row.append(pdf);}card.append(row);});
  const close=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Fechar"});close.addEventListener("click",closeModal);card.append(close);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");close.focus();
}
async function openFinalContent(version,documentType){const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-preview-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"finalDocumentTitle"}}),organizationId=await getActiveOrganizationId(),identityRow=await loadDocumentIdentity(organizationId,version.document_identity_id),logo=await documentPdfLogo(identityRow),logoDataUrl=identityRow?documentLogoDataUrl(identityRow):null,organization=(await supabaseRequest(`/rest/v1/organizations?id=eq.${encodeURIComponent(organizationId)}&select=id,name,trade_name,public_phone,public_whatsapp,creci,commercial_signature`))[0]||{},identity=documentIdentitySnapshot(version.identity_snapshot,organization);card.append(createElement("h2",{id:"finalDocumentTitle",text:`Documento v${version.version_no}`}),createDocumentPreviewPages({title:DOCUMENT_TYPE_LABELS[documentType]||"Documento imobiliário",content:version.rendered_content,identity,logo,logoDataUrl,versionLabel:`Documento v${version.version_no} · Modelo ${version.template_code} v${version.template_version}`}));const close=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Fechar"});close.addEventListener("click",closeModal);card.append(close);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");close.focus();}

async function openDocumentEditor(workspace,documentRecord=null,currentVersion=null){
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-editor-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"documentEditorTitle"}}),form=createElement("form",{className:"crm-form document-form"}),error=createElement("p",{className:"form-error",attrs:{role:"alert"}}),typeLabel=createElement("label",{text:"Tipo de documento *"}),typeSelect=createElement("select",{attrs:{required:""}}),templateInfo=createElement("p",{className:"muted document-template-info"}),fieldsMount=createElement("div",{className:"document-fields"});
  const existingDocument=Boolean(documentRecord?.id);Object.entries(DOCUMENT_TYPE_LABELS).forEach(([value,label])=>typeSelect.append(new Option(label,value)));typeSelect.value=documentRecord?.document_type||"sale_intermediation";if(existingDocument)typeSelect.disabled=true;typeLabel.append(typeSelect);
  const refs=createElement("fieldset",{className:"form-section document-reference-grid"});refs.append(createElement("legend",{text:"Dados do CRM"}));
  const propertyRef=createDocumentReferenceSelect("Imóvel",workspace.properties,documentPropertyId,item=>`${item.codigo} · ${item.titulo}`,documentRecord?.property_id),ownerRef=createDocumentReferenceSelect("Proprietário / vendedor",workspace.owners,item=>item.id,item=>item.full_name,documentRecord?.owner_id),leadRef=createDocumentReferenceSelect("Comprador / lead",workspace.leads,item=>item.id,item=>item.name,documentRecord?.lead_id),proposalRef=createDocumentReferenceSelect("Proposta / negócio",workspace.proposals,item=>item.id,item=>`${workspace.leads.find(lead=>lead.id===item.lead_id)?.name||"Lead"} · ${formatPrice(item.proposed_price)}`,documentRecord?.proposal_id);refs.append(propertyRef.label,ownerRef.label,leadRef.label,proposalRef.label);
  const prefill=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Preencher com dados do CRM"});refs.append(prefill);
  let inputs={},previewResult=null,payloadBase=currentVersion?.data_snapshot||{};
  function currentTemplate(){return workspace.templates.find(item=>item.document_type===typeSelect.value);}
  function drawFields(payload=payloadBase){inputs={};fieldsMount.replaceChildren();const section=createElement("fieldset",{className:"form-section"});section.append(createElement("legend",{text:"Conteúdo controlado"}));DOCUMENT_FIELDS[typeSelect.value].forEach(def=>{const built=createDocumentInput(def,payload?.[def[0]]??"");inputs[built.key]=built.input;section.append(built.label);});fieldsMount.append(section);const template=currentTemplate();templateInfo.textContent=template?`Modelo controlado ${template.template_code} v${template.version} · revisão de fontes: ${formatDate(template.legal_reviewed_at)}${template.status==="legal_review_required"?" · revisão jurídica profissional recomendada antes da assinatura":""}`:"Modelo indisponível";previewResult=null;}
  drawFields();typeSelect.addEventListener("change",()=>{payloadBase={};drawFields({});});
  prefill.addEventListener("click",async()=>{prefill.disabled=true;try{const values=await callCrmRpc("get_real_estate_document_prefill",{target_organization:workspace.org,target_type:typeSelect.value,target_property:propertyRef.select.value||null,target_owner:ownerRef.select.value||null,target_lead:leadRef.select.value||null,target_proposal:proposalRef.select.value||null});Object.entries(values||{}).forEach(([key,value])=>{if(inputs[key]&&!inputs[key].value){inputs[key].value=key==="offer_price"||key==="price"?new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(Number(value)):String(value);inputs[key].dispatchEvent(new Event("input",{bubbles:true}));}});showToast("Dados disponíveis preenchidos. Revise os campos antes de continuar.");}catch(reason){error.textContent=crmFriendlyError(reason,"Não foi possível reutilizar os dados do CRM.");}finally{prefill.disabled=false;}});
  function payload(){return Object.fromEntries(Object.entries(inputs).map(([key,input])=>[key,input.dataset.rawValue!==undefined?(input.dataset.rawValue||null):input.value.trim()||null]));}
  const summaryLabel=createElement("label",{text:"Resumo das alterações (opcional)"}),summary=createElement("input",{type:"text",attrs:{maxlength:"500",placeholder:existingDocument?"Ex.: ajuste das condições comerciais":"Ex.: primeira minuta"}});summary.value=currentVersion?._summary||"";summaryLabel.append(summary);
  const actions=createElement("div",{className:"modal-actions document-editor-actions"}),close=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Cancelar"}),preview=createElement("button",{type:"submit",className:"crm-button crm-button-primary",text:"Visualizar preview"});close.addEventListener("click",closeModal);actions.append(close,preview);
  form.append(typeLabel,templateInfo,refs,fieldsMount,summaryLabel,error,actions);form.addEventListener("submit",async event=>{event.preventDefault();if(preview.disabled)return;preview.disabled=true;error.textContent="";try{const template=currentTemplate();if(!template)throw new Error("Modelo indisponível.");previewResult=await callCrmRpc("preview_real_estate_document",{target_organization:workspace.org,target_template:template.id,target_payload:payload(),target_document:documentRecord?.id||null});await openDocumentPreview({workspace,documentRecord,documentType:typeSelect.value,formPayload:payload(),refs:{property:propertyRef.select.value||null,owner:ownerRef.select.value||null,lead:leadRef.select.value||null,proposal:proposalRef.select.value||null},summary:summary.value,previewResult});}catch(reason){error.textContent=crmFriendlyError(reason,"Não foi possível gerar o preview. Revise os dados e a identidade documental.");}finally{preview.disabled=false;}});
  card.append(createElement("h2",{id:"documentEditorTitle",text:existingDocument?`Nova versão · ${DOCUMENT_TYPE_LABELS[documentRecord.document_type]}`:"Novo documento"}),createElement("p",{className:"muted",text:"Campos ausentes permanecem destacados como preenchimento necessário. O preview é obrigatório antes de salvar ou finalizar."}),form);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");typeSelect.focus();
}

async function openDocumentPreview({workspace,documentRecord,documentType,formPayload,refs,summary,previewResult}){
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-preview-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"documentPreviewTitle"}}),missing=previewResult.missing_fields||[],error=createElement("p",{className:"form-error",attrs:{role:"alert"}});card.append(createElement("h2",{id:"documentPreviewTitle",text:"Preview obrigatório"}));
  if(missing.length){const warning=createElement("div",{className:"document-missing"});warning.append(createElement("strong",{text:"Preenchimento necessário antes de finalizar:"}),createElement("p",{text:missing.map(key=>documentMissingLabel(key,documentType)).join(" · ")}));card.append(warning);}
  const identityRow=previewResult.document_identity_id===workspace.identity?.id?workspace.identity:await loadDocumentIdentity(workspace.org,previewResult.document_identity_id),logo=await documentPdfLogo(identityRow),identity=documentIdentitySnapshot(previewResult.identity_snapshot,workspace.organization),logoDataUrl=identityRow?documentLogoDataUrl(identityRow):null;card.append(createDocumentPreviewPages({title:DOCUMENT_TYPE_LABELS[documentType],content:previewResult.content,identity,logo,logoDataUrl,versionLabel:`Preview · Modelo ${previewResult.template_code} v${previewResult.template_version}`}));const actions=createElement("div",{className:"modal-actions"}),back=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Voltar e revisar"}),draft=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Salvar rascunho"}),review=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Enviar para revisão"}),finalize=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"Finalizar versão"});finalize.disabled=missing.length>0;review.disabled=missing.length>0;
  back.addEventListener("click",async()=>{closeModal();const editableDocument=documentRecord?.id?documentRecord:{document_type:documentType,property_id:refs.property,owner_id:refs.owner,lead_id:refs.lead,proposal_id:refs.proposal};await openDocumentEditor(await loadDocumentWorkspace(),editableDocument,{data_snapshot:formPayload,_summary:summary});});
  async function save(targetStatus){if(draft.disabled)return;[draft,review,finalize,back].forEach(button=>button.disabled=true);error.textContent="";try{const saved=await callCrmRpc("save_real_estate_document_version",{target_organization:workspace.org,target_preview:previewResult.preview_id,target_payload:formPayload,target_document:documentRecord?.id||null,target_property:refs.property,target_owner:refs.owner,target_lead:refs.lead,target_proposal:refs.proposal,target_changes_summary:summary||null});if(targetStatus==="review")await callCrmRpc("submit_real_estate_document_review",{target_organization:workspace.org,target_document:saved.document_id,target_version:saved.version_no});if(targetStatus==="finalized")await callCrmRpc("finalize_real_estate_document",{target_organization:workspace.org,target_document:saved.document_id,target_version:saved.version_no});closeModal();showToast(targetStatus==="finalized"?"Documento finalizado e protegido.":targetStatus==="review"?"Documento enviado para revisão.":"Rascunho versionado salvo.");await renderCurrentView();}catch(reason){error.textContent=crmFriendlyError(reason,"Não foi possível salvar o documento.");[draft,back].forEach(button=>button.disabled=false);review.disabled=missing.length>0;finalize.disabled=missing.length>0;}}
  draft.addEventListener("click",()=>save("draft"));review.addEventListener("click",()=>save("review"));finalize.addEventListener("click",()=>save("finalized"));actions.append(back,draft,review,finalize);card.append(error,actions);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");back.focus();
}
