const DOCUMENT_TYPE_LABELS={sale_intermediation:"Contrato de corretagem para venda",property_sale_purchase:"Instrumento de compra e venda · minuta"};
const DOCUMENT_STATUS_LABELS={draft:"Rascunho",review:"Em revisão",finalized:"Finalizado",canceled:"Cancelado"};
const DOCUMENT_AUTOFILL_FIELDS={property:["property_description","offer_price","price","city"],owner:["seller_name","seller_contact"],lead:["buyer_name","buyer_contact"],proposal:["price"],professional:["broker_name","broker_qualification","broker_creci","broker_contact","document_date"]};
let pendingDocumentReferenceFilter=null;
function openDocumentsForReference(kind,id,label){pendingDocumentReferenceFilter={kind,id,label};closeModal();navigateCrm("documents");}
const DOCUMENT_STEPS={
  sale_intermediation:[["document","Documento"],["parties","Partes"],["property","Imóvel"],["conditions","Condições"],["legal","Jurídico"],["review","Revisão"]],
  property_sale_purchase:[["document","Documento"],["scenario","Cenário"],["parties","Partes"],["property","Imóvel"],["conditions","Condições"],["legal","Jurídico"],["review","Revisão"]]
};
const DOCUMENT_FIELDS={
  sale_intermediation:[
    ["seller_name","Proprietário / contratante","text",true,null,"parties"],["seller_qualification","Qualificação completa do contratante","textarea",true,null,"parties"],["seller_contact","E-mail e telefone do contratante","text",false,null,"parties"],
    ["broker_name","Corretor(a) / imobiliária","text",true,null,"parties"],["broker_qualification","Qualificação do corretor ou responsável da imobiliária","textarea",true,null,"parties"],["broker_creci","CRECI, região/UF e tipo do registro","text",true,null,"parties"],["broker_contact","E-mail e telefone do corretor","text",false,null,"parties"],
    ["property_description","Descrição e endereço completo do imóvel","textarea",true,null,"property"],["registry_information","Matrícula, cartório/circunscrição e registro aplicável","textarea",true,null,"property"],["documents_presented","Documentos apresentados pelo contratante","textarea",true,null,"property"],
    ["offer_price","Preço de oferta","currency",true,null,"conditions"],["commercial_conditions","Condições comerciais e de pagamento","textarea",true,null,"conditions"],["remuneration_terms","Percentual ou valor fixo dos honorários","textarea",true,null,"conditions"],["term_text","Prazo em dias ou meses corridos","text",true,null,"conditions"],["exclusivity","Tipo de contratação","select",true,{exclusive:"Com exclusividade",non_exclusive:"Sem exclusividade"},"conditions"],
    ["publicity_authorization","Meios de publicidade expressamente autorizados","textarea",true,null,"legal"],["substitution_authorization","Atuação com outro profissional habilitado","select",true,{allowed:"Autorizada, sob responsabilidade do contratado",not_allowed:"Depende de anuência expressa"},"legal"],["sgr_consultation","Consulta prévia do objeto no SGR","select",true,{confirmed:"Confirmada pelo usuário",pending:"Ainda pendente"},"legal"],["signature_method","Meio previsto para assinatura","select",true,{physical:"Assinatura física",electronic_advanced:"Assinatura eletrônica avançada ou superior, em serviço externo"},"legal"],["closing_terms","Condições de encerramento","textarea",true,null,"legal"],
    ["city","Local","text",true,null,"review"],["document_date","Data","date",true,null,"review"]
  ],
  property_sale_purchase:[
    ["instrument_nature","Natureza pretendida para a minuta","select",true,{preliminary_commitment:"Compromisso preliminar",purchase_sale_contract:"Contrato obrigacional de compra e venda"},"scenario"],["property_regime","Imóvel urbano ou rural?","select",true,{urban:"Urbano",rural:"Rural · exige análise específica"},"scenario"],["property_stage","Situação do imóvel","select",true,{ready:"Pronto / usado",development:"Empreendimento / unidade futura · exige análise específica"},"scenario"],["special_regime","Regime especial","select",true,{none:"Nenhum informado",incorporation:"Incorporação imobiliária",subdivision:"Loteamento"},"scenario"],["financing_option","Haverá financiamento?","select",true,{none:"Não",applicable:"Sim · exige compatibilização"},"scenario"],["financing_terms","Condições do financiamento","textarea",false,null,"scenario",{key:"financing_option",value:"applicable"}],["fiduciary_lien","Existe alienação fiduciária/gravame relacionado?","select",true,{none:"Não informado",applicable:"Sim · exige análise específica"},"scenario"],["consumer_relationship","Pode existir relação de consumo?","select",true,{no:"Não identificada",possible:"Possivelmente · exige análise específica"},"scenario"],["coowners_option","Há coproprietários?","select",true,{none:"Não",applicable:"Sim"},"scenario"],["coowners_details","Identificação e participação dos coproprietários","textarea",false,null,"scenario",{key:"coowners_option",value:"applicable"}],
    ["seller_name","Vendedor(es)","text",true,null,"parties"],["seller_type","Tipo de vendedor","select",true,{individual:"Pessoa física",company:"Pessoa jurídica"},"parties"],["seller_qualification","Qualificação completa do(s) vendedor(es)","textarea",true,null,"parties"],["seller_contact","E-mail e telefone do(s) vendedor(es)","text",false,null,"parties"],["buyer_name","Comprador(es)","text",true,null,"parties"],["buyer_type","Tipo de comprador","select",true,{individual:"Pessoa física",company:"Pessoa jurídica"},"parties"],["buyer_qualification","Qualificação completa do(s) comprador(es)","textarea",true,null,"parties"],["buyer_contact","E-mail e telefone do(s) comprador(es)","text",false,null,"parties"],
    ["property_description","Identificação completa do imóvel","textarea",true,null,"property"],["registry_status","Matrícula/registro conferido?","select",true,{available:"Sim, disponível para conferência",unavailable:"Não · exige análise específica"},"property"],["registry_information","Matrícula, cartório e circunscrição","textarea",false,null,"property",{key:"registry_status",value:"available"}],["debts_terms","Débitos, ônus e declarações conhecidos","textarea",true,null,"property"],
    ["price","Preço","currency",true,null,"conditions"],["payment_terms","Forma de pagamento e parcelas","textarea",true,null,"conditions"],["arras_option","Haverá sinal / arras?","select",true,{none:"Não",applicable:"Sim · detalhar"},"conditions"],["arras_terms","Condições e natureza do sinal / arras","textarea",false,null,"conditions",{key:"arras_option",value:"applicable"}],["possession_terms","Condições e data da posse","textarea",true,null,"conditions"],
    ["deed_transfer_terms","Formalização, escritura/título e registro conforme o caso","textarea",true,null,"legal"],["taxes_expenses_terms","Tributos e despesas","textarea",true,null,"legal"],["brokerage_terms","Corretagem","textarea",true,null,"legal"],["default_terms","Inadimplemento, atualização e juros","textarea",true,null,"legal"],["termination_terms","Rescisão","textarea",true,null,"legal"],
    ["city","Local","text",true,null,"review"],["document_date","Data","date",true,null,"review"],["witnesses","Testemunhas, se previstas/aplicáveis","textarea",false,null,"review"]
  ]
};

async function loadDocumentWorkspace(){
  const org=await getActiveOrganizationId();
  const [templates,documents,versions,properties,owners,leads,proposals,organizations]=await Promise.all([
    supabaseRequest("/rest/v1/document_templates?status=in.(active,legal_review_required)&select=*&order=template_code,version.desc"),
    supabaseRequest(`/rest/v1/real_estate_documents?organization_id=eq.${encodeURIComponent(org)}&archived_at=is.null&select=*&order=updated_at.desc`),
    supabaseRequest(`/rest/v1/real_estate_document_versions?organization_id=eq.${encodeURIComponent(org)}&select=*&order=version_no.desc`),
    loadProperties(),
    supabaseRequest(`/rest/v1/property_owners?organization_id=eq.${encodeURIComponent(org)}&select=id,full_name,phone,email,assigned_to,status&order=full_name`),
    getLeads(),getProposals().catch(()=>[]),supabaseRequest(`/rest/v1/organizations?id=eq.${encodeURIComponent(org)}&select=id,name,trade_name,public_phone,public_whatsapp,creci,commercial_signature,current_document_identity_id`)
  ]);
  const organization=organizations[0]||{},identity=organization.current_document_identity_id?await loadDocumentIdentity(org,organization.current_document_identity_id):null;
  return{org,templates,documents,versions,properties,owners,leads,proposals,organization,identity};
}
async function loadDocumentIdentity(organizationId,identityId){if(!identityId)return null;const rows=await supabaseRequest(`/rest/v1/organization_document_identities?id=eq.${encodeURIComponent(identityId)}&organization_id=eq.${encodeURIComponent(organizationId)}&select=id,version_no,logo_bytes,logo_mime_type,logo_width,logo_height,logo_sha256,created_at`);return rows[0]||null;}
function documentIdentitySnapshot(snapshot={},organization={}){return{organization_name:snapshot.organization_name||organization.name||null,trade_name:snapshot.trade_name||organization.trade_name||null,public_phone:snapshot.public_phone||organization.public_phone||null,public_whatsapp:snapshot.public_whatsapp||organization.public_whatsapp||null,creci:snapshot.creci||organization.creci||null,commercial_signature:snapshot.commercial_signature||organization.commercial_signature||null,...snapshot};}
async function documentPdfLogo(identity){if(!identity?.logo_bytes)return null;return prepareDocumentLogoForPdf({bytes:documentLogoBytes(identity.logo_bytes),mime:identity.logo_mime_type,width:identity.logo_width,height:identity.logo_height});}
function documentPropertyId(item){return item?._row?.id||item?.id||null;}
function appendSelectOptions(select,items,valueOf,labelOf,emptyLabel){select.replaceChildren(new Option(emptyLabel||"Não vincular",""));items.forEach(item=>select.append(new Option(labelOf(item),valueOf(item))));}
function createDocumentReferenceSelect(labelText,items,valueOf,labelOf,selected="") {const label=createElement("label",{text:labelText}),select=createElement("select");appendSelectOptions(select,items,valueOf,labelOf,"Não vincular");select.value=selected||"";label.append(select);return{label,select};}
function createDocumentInput(definition,value=""){
  const[key,labelText,kind,required,options,step,condition]=definition,label=createElement("label",{className:"document-control",text:`${labelText}${required?" *":""}`}),input=kind==="textarea"?createElement("textarea",{attrs:{rows:"3",maxlength:"5000"}}):kind==="select"?createElement("select"):createElement("input",{type:kind==="date"?"date":"text",attrs:{maxlength:"5000"}}),status=createElement("small",{className:"document-field-status",attrs:{"aria-live":"polite"}});
  input.name=key;if(required)input.required=true;
  if(kind==="select"){input.append(new Option("Selecione",""));Object.entries(options).forEach(([optionValue,optionLabel])=>input.append(new Option(optionLabel,optionValue)));}
  input.value=value==null?"":String(value);if(kind==="currency")bindCurrencyInput(input);if(condition){label.dataset.conditionKey=condition.key;label.dataset.conditionValue=condition.value;}label.append(input,status);return{label,input,status,key,kind,required,step:step||"conditions"};
}
function documentMissingLabel(key,type){return DOCUMENT_FIELDS[type]?.find(field=>field[0]===key)?.[1]||key;}
function documentSafeFilename(document,version){return `vc-imob-${document.document_type}-${document.id.slice(0,8)}-v${version.version_no}.pdf`;}
function documentVersionLabel(version){return `Modelo ${version.template_code} v${version.template_version} · Base jurídica ${version.legal_basis_version||"legada"}`;}
function createDocumentChecklist(items=[]){const section=createElement("section",{className:"document-checklist",attrs:{"aria-label":"Checklist pré-finalização"}});section.append(createElement("h3",{text:"Checklist pré-finalização"}));const list=createElement("ul");items.forEach(item=>{const row=createElement("li",{className:`document-check-${item.resolved?"ok":item.level||"attention"}`});row.append(createElement("span",{attrs:{"aria-hidden":"true"},text:item.resolved?"✓":item.level==="required"?"!":"i"}),createElement("span",{text:`${item.resolved?"Conferido":item.level==="required"?"Obrigatório":item.level==="attention"?"Atenção":"Informativo"}: ${item.label}`}));list.append(row);});section.append(list);return section;}
function createDocumentNextSteps(type){const section=createElement("section",{className:"document-next-steps"}),list=createElement("ol");section.append(createElement("h3",{text:"Próximos passos"}));const steps=type==="sale_intermediation"?["Revisar integralmente o contrato e os dados do quadro resumo.","Confirmar a consulta aplicável no SGR; o VC Imob não realiza esse registro.","Colher assinaturas pelo meio escolhido e guardar a versão efetivamente assinada fora do cache público."]:["Revisar a minuta com as partes e profissional jurídico quando necessário.","Confirmar o título e as formalidades adequadas ao cenário concreto.","Providenciar escritura ou instrumento legalmente admitido e o registro imobiliário quando aplicáveis.","Guardar separadamente a versão efetivamente assinada."];steps.forEach(text=>list.append(createElement("li",{text})));section.append(list);return section;}

async function renderDocuments(root){
  if(!await hasEntitlement("crm.documents")){root.replaceChildren(createFeatureNotice("Documentos","Disponível nos planos PRO e EQUIPE."));return;}
  if(isDemoMode()){root.replaceChildren(createEmptyState("Documentos indisponíveis na demonstração","Este módulo exige uma organização autenticada para preservar dados privados e versões."));return;}
  const workspace=await loadDocumentWorkspace();if(!root.isConnected)return;root.replaceChildren();
  const toolbar=createElement("div",{className:"toolbar document-toolbar"}),create=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"+ Novo documento"});
  create.addEventListener("click",async()=>{if(create.disabled)return;create.disabled=true;try{await openDocumentEditor(workspace);}catch(error){console.error("Document editor failed",{operation:"open_document_editor",code:error?.code||"unexpected_error"});showToast(crmFriendlyError(error,"Não foi possível abrir o novo documento. Tente novamente."),"error");}finally{create.disabled=false;}});const activeDocuments=pendingDocumentReferenceFilter?workspace.documents.filter(item=>item[`${pendingDocumentReferenceFilter.kind}_id`]===pendingDocumentReferenceFilter.id):workspace.documents;const caption=createElement("p",{className:"muted",text:pendingDocumentReferenceFilter?`Histórico relacionado a ${pendingDocumentReferenceFilter.label}`:`${workspace.documents.length} documento(s) no histórico`});toolbar.append(caption);if(pendingDocumentReferenceFilter){const clear=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Ver todos"});clear.addEventListener("click",()=>{pendingDocumentReferenceFilter=null;renderCurrentView();});toolbar.append(clear);}toolbar.append(create);root.append(toolbar);
  const notice=createElement("section",{className:"crm-panel document-legal-notice"});notice.append(createElement("strong",{text:"Modelos controlados e versionados"}),createElement("p",{text:"O módulo reaproveita dados do CRM, exige preview e não substitui revisão jurídica profissional. Não há assinatura eletrônica nesta etapa."}));root.append(notice);
  const list=createElement("section",{className:"document-list"});
  if(!activeDocuments.length)list.append(createEmptyState("Nenhum documento encontrado","Crie um rascunho, revise todos os campos e visualize o conteúdo antes de finalizar."));
  activeDocuments.forEach(document=>{
    const version=workspace.versions.find(item=>item.document_id===document.id&&item.version_no===document.current_version),property=workspace.properties.find(item=>documentPropertyId(item)===document.property_id),owner=workspace.owners.find(item=>item.id===document.owner_id),lead=workspace.leads.find(item=>item.id===document.lead_id),card=createElement("article",{className:"crm-panel document-card"});
    const heading=createElement("div",{className:"document-card-heading"});heading.append(createElement("div",{className:"min-width-zero"}),createElement("span",{className:`stage document-status-${document.status}`,text:DOCUMENT_STATUS_LABELS[document.status]||document.status}));heading.firstChild.append(createElement("h2",{text:DOCUMENT_TYPE_LABELS[document.document_type]}),createElement("p",{className:"muted",text:`Versão ${document.current_version} · ${version?documentVersionLabel(version):"modelo legado"} · ${formatDate(document.updated_at,true)}`}));card.append(heading);
    card.append(createElement("p",{text:[property?.codigo,owner?.full_name,lead?.name].filter(Boolean).join(" · ")||"Sem vínculo complementar"}));
    const actions=createElement("div",{className:"property-admin-actions document-actions"}),open=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Abrir histórico"});open.addEventListener("click",()=>openDocumentHistory(workspace,document));actions.append(open);
    if(document.status!=="canceled"){const edit=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:document.status==="finalized"?"Criar nova versão":"Revisar / editar"});edit.addEventListener("click",()=>openDocumentEditor(workspace,document,version));actions.append(edit);}
    if(version?.status==="finalized"){const pdf=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"Gerar PDF"});pdf.addEventListener("click",()=>generateDocumentPdf(document,version));actions.append(pdf);}
    if(document.status!=="canceled"){const cancel=createElement("button",{type:"button",className:"crm-button crm-button-danger",text:"Cancelar documento"});cancel.addEventListener("click",()=>openDestructiveConfirmation({title:"Cancelar documento?",message:"O histórico e as versões serão preservados. Esta ação não apaga o conteúdo auditável.",confirmLabel:"Cancelar documento",busyLabel:"Cancelando…",successMessage:"Documento cancelado.",fallbackError:"Não foi possível cancelar o documento.",onConfirm:async()=>{await callCrmRpc("cancel_real_estate_document",{target_organization:workspace.org,target_document:document.id});await renderCurrentView();}}));actions.append(cancel);}
    card.append(actions);list.append(card);
  });root.append(list);
}

async function generateDocumentPdf(document,version){
  try{const organizationId=await getActiveOrganizationId(),identity=await loadDocumentIdentity(organizationId,version.document_identity_id),logo=await documentPdfLogo(identity),organization=(await supabaseRequest(`/rest/v1/organizations?id=eq.${encodeURIComponent(organizationId)}&select=id,name,trade_name,public_phone,public_whatsapp,creci,commercial_signature`))[0]||{};await callCrmRpc("record_real_estate_document_pdf",{target_organization:organizationId,target_document:document.id,target_version:version.version_no});downloadRealEstateDocumentPdf({title:DOCUMENT_TYPE_LABELS[document.document_type],content:version.rendered_content,identity:documentIdentitySnapshot(version.identity_snapshot,organization),logo,versionLabel:`Documento v${version.version_no} · ${documentVersionLabel(version)}`,documentIdentifier:`${document.id.slice(0,8).toUpperCase()}-V${version.version_no}`,generatedAt:new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date()),filename:documentSafeFilename(document,version)});showToast("PDF gerado. Revise e siga os próximos passos indicados no documento.");}catch(error){console.error("Document PDF failed",{operation:"generate_document_pdf",code:error?.code||"invalid_logo_or_pdf"});showToast(crmFriendlyError(error,"Não foi possível gerar o PDF. Verifique a identidade documental e tente novamente."),"error");}
}

function createDocumentPreviewPages({title,content,identity,logo,logoDataUrl,versionLabel,documentIdentifier="PREVIEW"}){const host=createElement("div",{className:"document-preview-pages"}),pages=layoutRealEstateDocumentPdf({title,content,identity,logo});pages.forEach((page,index)=>{const sheet=createElement("section",{className:"document-preview-page",attrs:{"aria-label":`Página ${index+1} de ${pages.length}`}});if(index===0&&logoDataUrl)sheet.append(createElement("img",{attrs:{src:logoDataUrl,alt:`Logo de ${identity.trade_name||identity.organization_name||"organização"}`}}));else if(index===0)sheet.append(createElement("strong",{text:identity.trade_name||identity.organization_name||"Documento imobiliário"}));if(index===0)sheet.append(createElement("div",{className:"document-preview-meta",text:`ID ${documentIdentifier} · ${versionLabel}`}),createElement("h3",{text:title}));page.elements.forEach(item=>sheet.append(createElement("p",{className:item.font==="bold"?"document-preview-heading":"",text:item.text})));const footer=createElement("footer");footer.append(createElement("span",{text:`${documentIdentifier} · ${versionLabel}`}),createElement("span",{text:`Página ${index+1} de ${pages.length}`}));sheet.append(footer);host.append(sheet);});return host;}

function openDocumentHistory(workspace,documentRecord){
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-history-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"documentHistoryTitle"}});card.append(createElement("h2",{id:"documentHistoryTitle",text:"Histórico do documento"}),createElement("p",{className:"muted",text:`${DOCUMENT_TYPE_LABELS[documentRecord.document_type]} · ${DOCUMENT_STATUS_LABELS[documentRecord.status]}`}));
  workspace.versions.filter(item=>item.document_id===documentRecord.id).sort((a,b)=>b.version_no-a.version_no).forEach(version=>{const row=createElement("article",{className:"document-version-row"}),summary=createElement("div",{className:"min-width-zero"});summary.append(createElement("strong",{text:`Versão ${version.version_no}`}),createElement("span",{text:`${DOCUMENT_STATUS_LABELS[version.status]} · ${documentVersionLabel(version)} · ${formatDate(version.created_at,true)}`}),createElement("small",{text:version.changes_summary||"Sem resumo de alterações."}));const preview=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Visualizar"});preview.addEventListener("click",async()=>{preview.disabled=true;try{await openFinalContent(version,documentRecord.document_type);}catch(error){showToast(crmFriendlyError(error,"Não foi possível abrir esta versão."),"error");}finally{preview.disabled=false;}});row.append(summary,preview);if(version.status==="finalized"){const pdf=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"PDF"});pdf.addEventListener("click",()=>generateDocumentPdf(documentRecord,version));row.append(pdf);}card.append(row);});
  const historyActions=createElement("div",{className:"modal-actions document-history-actions"}),remove=createElement("button",{type:"button",className:"crm-button crm-button-danger-ghost document-delete-action",text:"🗑 Excluir documento",attrs:{"aria-label":"Excluir documento"}}),close=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Fechar"});
  remove.addEventListener("click",()=>{const hasFinalized=workspace.versions.some(version=>version.document_id===documentRecord.id&&version.status==="finalized"),willArchive=documentRecord.status==="finalized"||hasFinalized;openDestructiveConfirmation({title:"Excluir este documento?",message:willArchive?"O documento será removido da lista principal, mas a versão finalizada, seus snapshots e o histórico auditável serão preservados.":"O documento e suas versões não finalizadas serão excluídos permanentemente. Esta ação não pode ser desfeita.",confirmLabel:"Excluir",busyLabel:"Excluindo…",successMessage:willArchive?"Documento arquivado e removido da lista principal.":"Documento excluído.",fallbackError:"Não foi possível excluir o documento.",onConfirm:async()=>{await callCrmRpc("delete_real_estate_document",{target_organization:workspace.org,target_document:documentRecord.id});await renderCurrentView();}});});
  close.addEventListener("click",closeModal);historyActions.append(remove,close);card.append(historyActions);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");close.focus();
}
async function openFinalContent(version,documentType){const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-preview-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"finalDocumentTitle"}}),organizationId=await getActiveOrganizationId(),identityRow=await loadDocumentIdentity(organizationId,version.document_identity_id),logo=await documentPdfLogo(identityRow),logoDataUrl=identityRow?documentLogoDataUrl(identityRow):null,organization=(await supabaseRequest(`/rest/v1/organizations?id=eq.${encodeURIComponent(organizationId)}&select=id,name,trade_name,public_phone,public_whatsapp,creci,commercial_signature`))[0]||{},identity=documentIdentitySnapshot(version.identity_snapshot,organization);card.append(createElement("h2",{id:"finalDocumentTitle",text:`Documento v${version.version_no}`}),createDocumentPreviewPages({title:DOCUMENT_TYPE_LABELS[documentType]||"Documento imobiliário",content:version.rendered_content,identity,logo,logoDataUrl,versionLabel:`Documento v${version.version_no} · ${documentVersionLabel(version)}`,documentIdentifier:`VERSÃO-${version.version_no}`}),createDocumentChecklist(version.legal_checklist||[]),createDocumentNextSteps(documentType));const close=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Fechar"});close.addEventListener("click",closeModal);card.append(close);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");close.focus();}

async function openDocumentEditor(workspace,documentRecord=null,currentVersion=null){
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-editor-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"documentEditorTitle","data-modal-chrome":"true"}}),form=createElement("form",{className:"crm-form document-form"}),body=createElement("div",{className:"document-editor-body"}),error=createElement("p",{className:"form-error",attrs:{role:"alert"}}),typeLabel=createElement("label",{text:"Tipo de documento *"}),typeSelect=createElement("select",{attrs:{required:""}}),templateInfo=createElement("p",{className:"muted document-template-info"}),progress=createElement("nav",{className:"document-progress",attrs:{"aria-label":"Etapas do documento"}}),fieldsMount=createElement("div",{className:"document-fields"}),stepCounter=createElement("p",{className:"document-step-counter",attrs:{"aria-live":"polite"}}),mobileStepCounter=createElement("p",{className:"document-step-counter document-mobile-step-counter",attrs:{"aria-live":"polite",tabindex:"-1"}});
  const existingDocument=Boolean(documentRecord?.id);Object.entries(DOCUMENT_TYPE_LABELS).forEach(([value,label])=>typeSelect.append(new Option(label,value)));typeSelect.value=documentRecord?.document_type||"sale_intermediation";if(existingDocument)typeSelect.disabled=true;typeLabel.append(typeSelect);
  const refs=createElement("fieldset",{className:"form-section document-reference-grid document-step-panel"});refs.dataset.documentStep="document";refs.append(createElement("legend",{text:"Dados existentes no CRM"}),createElement("p",{className:"document-step-help",text:"Ao selecionar um registro, os dados reais disponíveis são preenchidos automaticamente e continuam editáveis."}));
  const propertyRef=createDocumentReferenceSelect("Imóvel",workspace.properties,documentPropertyId,item=>`${item.codigo} · ${item.titulo}`,documentRecord?.property_id),ownerRef=createDocumentReferenceSelect("Proprietário / vendedor",workspace.owners,item=>item.id,item=>item.full_name,documentRecord?.owner_id),leadRef=createDocumentReferenceSelect("Comprador / lead",workspace.leads,item=>item.id,item=>item.name,documentRecord?.lead_id),proposalRef=createDocumentReferenceSelect("Proposta / negócio",workspace.proposals,item=>item.id,item=>`${workspace.leads.find(lead=>lead.id===item.lead_id)?.name||"Lead"} · ${formatPrice(item.proposed_price)}`,documentRecord?.proposal_id);refs.append(propertyRef.label,ownerRef.label,leadRef.label,proposalRef.label);
  const prefill=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Atualizar dados do CRM"}),identityHint=createElement("p",{className:"document-crm-origin",text:workspace.identity?"✓ Identidade documental configurada no CRM":"Identidade documental ainda não configurada"});refs.append(prefill,identityHint);
  const summaryLabel=createElement("label",{className:"document-control",text:"Resumo das alterações (opcional)"}),summary=createElement("input",{type:"text",attrs:{maxlength:"500",placeholder:existingDocument?"Ex.: ajuste das condições comerciais":"Ex.: primeira minuta"}});summary.value=currentVersion?._summary||"";summaryLabel.append(summary);
  let inputs={},inputMeta={},previewResult=null,payloadBase=currentVersion?.data_snapshot||{},stepIndex=0,stepPanels=[],applyingAutofill=false;
  let manualFields=new Set(Object.entries(payloadBase).filter(([,value])=>value!==null&&value!=="").map(([key])=>key)),fieldOrigins={},lastAutofill={},referenceAuto={},referenceManual={property:Boolean(documentRecord?.property_id),owner:Boolean(documentRecord?.owner_id),lead:Boolean(documentRecord?.lead_id),proposal:Boolean(documentRecord?.proposal_id)};
  function currentTemplate(){return workspace.templates.find(item=>item.document_type===typeSelect.value);}
  const title=createElement("h2",{id:"documentEditorTitle",text:existingDocument?`Nova versão · ${DOCUMENT_TYPE_LABELS[documentRecord.document_type]}`:"Novo documento"}),header=createElement("header",{className:"document-editor-header"}),headerBack=createElement("button",{type:"button",className:"document-editor-header-back",text:"← Voltar",attrs:{"aria-label":"Voltar para a etapa anterior"}}),headerCenter=createElement("div",{className:"document-editor-header-center"}),headerClose=createElement("button",{type:"button",className:"modal-close-button document-editor-close",text:"×",attrs:{"aria-label":"Cancelar edição do documento","data-modal-close":"true"}}),intro=createElement("p",{className:"muted document-editor-intro",text:"Fluxo guiado com campos condicionais. Dados incompletos podem ser salvos como rascunho; cenários especiais não podem ser finalizados sem análise adequada."});headerCenter.append(mobileStepCounter,title);header.append(headerBack,headerCenter,headerClose);headerClose.addEventListener("click",closeModal);
  const actions=createElement("div",{className:"modal-actions document-editor-actions"}),close=createElement("button",{type:"button",className:"crm-button crm-button-outline document-action-cancel",text:"Cancelar"}),previous=createElement("button",{type:"button",className:"crm-button crm-button-outline document-action-previous",text:"Voltar"}),next=createElement("button",{type:"button",className:"crm-button crm-button-outline document-action-next",text:"Continuar"}),preview=createElement("button",{type:"submit",className:"crm-button crm-button-primary document-action-preview",text:"Gerar revisão e preview"});close.addEventListener("click",closeModal);actions.append(close,previous,next,preview);
  function refreshConditionalFields(){fieldsMount.querySelectorAll("[data-condition-key]").forEach(label=>{const source=inputs[label.dataset.conditionKey],visible=source?.value===label.dataset.conditionValue;label.hidden=!visible;const control=label.querySelector("input,select,textarea");if(control)control.disabled=!visible;});}
  function refreshFieldStatus(key){const meta=inputMeta[key],input=inputs[key];if(!meta||!input)return;const filled=Boolean(input.value.trim()),status=meta.status;status.className="document-field-status";if(filled&&fieldOrigins[key]==="crm"){status.textContent="✓ Preenchido pelo CRM";status.classList.add("is-crm");}else if(filled){status.textContent="Preenchido manualmente";status.classList.add("is-manual");}else if(meta.required){status.textContent="Preenchimento necessário";status.classList.add("is-pending");}else status.textContent="";}
  function allAutofillKeys(source){if(source==="all")return Object.values(DOCUMENT_AUTOFILL_FIELDS).flat();if(source==="property")return [...DOCUMENT_AUTOFILL_FIELDS.property,...DOCUMENT_AUTOFILL_FIELDS.owner];if(source==="proposal")return [...DOCUMENT_AUTOFILL_FIELDS.proposal,...DOCUMENT_AUTOFILL_FIELDS.property,...DOCUMENT_AUTOFILL_FIELDS.owner,...DOCUMENT_AUTOFILL_FIELDS.lead];return DOCUMENT_AUTOFILL_FIELDS[source]||[];}
  function displayAutofillValue(key,value){return ["offer_price","price"].includes(key)&&value!==null&&value!==""?formatBrlInput(value):String(value??"");}
  function setAutomaticReference(name,value){const ref={property:propertyRef,owner:ownerRef,lead:leadRef,proposal:proposalRef}[name];if(!ref)return;if(referenceManual[name]&&ref.select.value!==referenceAuto[name])return;const next=value||"";if(ref.select.value!==next)ref.select.value=next;referenceAuto[name]=next;referenceManual[name]=false;}
  async function refreshAutofill(source="all"){
    const proposalCanResolve=source==="proposal",propertyCanResolveOwner=source==="property"||proposalCanResolve;
    const values=await callCrmRpc("get_real_estate_document_prefill",{target_organization:workspace.org,target_type:typeSelect.value,target_property:proposalCanResolve&&!referenceManual.property?null:propertyRef.select.value||null,target_owner:propertyCanResolveOwner&&!referenceManual.owner?null:ownerRef.select.value||null,target_lead:proposalCanResolve&&!referenceManual.lead?null:leadRef.select.value||null,target_proposal:proposalRef.select.value||null}),references=values?._references||{};
    if(source==="all"||source==="proposal"){setAutomaticReference("property",references.property_id);setAutomaticReference("lead",references.lead_id);}
    if(source==="all"||source==="proposal"||source==="property")setAutomaticReference("owner",references.owner_id);
    applyingAutofill=true;
    try{for(const key of allAutofillKeys(source)){const input=inputs[key];if(!input||manualFields.has(key))continue;const hasValue=values?.[key]!==undefined&&values?.[key]!==null&&values?.[key]!=="",next=hasValue?displayAutofillValue(key,values[key]):"";if(hasValue&&(input.value===""||fieldOrigins[key]==="crm")){input.value=next;fieldOrigins[key]="crm";lastAutofill[key]=next;}else if(!hasValue&&fieldOrigins[key]==="crm"&&input.value===lastAutofill[key]){input.value="";delete fieldOrigins[key];delete lastAutofill[key];}refreshFieldStatus(key);}}
    finally{applyingAutofill=false;}
    refreshConditionalFields();
  }
  function renderStep({focus=false}={}){const steps=DOCUMENT_STEPS[typeSelect.value],active=steps[stepIndex]||steps[0],label=`Etapa ${stepIndex+1} de ${steps.length} · ${active[1]}`;stepPanels.forEach(panel=>panel.hidden=panel.dataset.documentStep!==active[0]);progress.querySelectorAll("button").forEach((button,index)=>{button.classList.toggle("is-active",index===stepIndex);if(index===stepIndex)button.setAttribute("aria-current","step");else button.removeAttribute("aria-current");});stepCounter.textContent=label;mobileStepCounter.textContent=label;headerBack.disabled=stepIndex===0;previous.hidden=stepIndex===0;next.hidden=stepIndex===steps.length-1;preview.hidden=stepIndex!==steps.length-1;if(focus){if(window.matchMedia?.("(max-width: 600px)")?.matches){body.scrollTop=0;mobileStepCounter.focus({preventScroll:true});}else{const first=stepPanels.find(panel=>!panel.hidden)?.querySelector("input,select,textarea,button");first?.focus();}}}
  function goToStep(index){const steps=DOCUMENT_STEPS[typeSelect.value],target=Math.max(0,Math.min(index,steps.length-1));if(target===stepIndex)return;const active=document.activeElement;if(active instanceof HTMLElement&&card.contains(active))active.blur();stepIndex=target;renderStep({focus:true});}
  function drawFields(payload=payloadBase){inputs={};inputMeta={};fieldsMount.replaceChildren();progress.replaceChildren();const steps=DOCUMENT_STEPS[typeSelect.value],sections=new Map();steps.filter(([key])=>key!=="document").forEach(([key,title])=>{const section=createElement("fieldset",{className:"form-section document-step-panel"});section.dataset.documentStep=key;section.append(createElement("legend",{text:title}));sections.set(key,section);fieldsMount.append(section);});DOCUMENT_FIELDS[typeSelect.value].forEach(def=>{const built=createDocumentInput(def,payload?.[def[0]]??"");inputs[built.key]=built.input;inputMeta[built.key]=built;sections.get(built.step)?.append(built.label);const markManual=()=>{if(applyingAutofill)return;manualFields.add(built.key);fieldOrigins[built.key]="manual";refreshFieldStatus(built.key);};built.input.addEventListener("input",markManual);built.input.addEventListener("change",()=>{markManual();refreshConditionalFields();});refreshFieldStatus(built.key);});sections.get("review")?.append(summaryLabel,createElement("p",{className:"document-review-note",text:"Confira todos os dados. O preview não substitui revisão jurídica profissional e não certifica assinatura."}));steps.forEach(([key,title],index)=>{const button=createElement("button",{type:"button",text:`${index+1}. ${title}`,attrs:{"aria-label":`Ir para etapa ${index+1}: ${title}`}});button.addEventListener("click",()=>goToStep(index));progress.append(button);});stepPanels=[refs,...fieldsMount.querySelectorAll(".document-step-panel")];const template=currentTemplate();templateInfo.textContent=template?`Modelo ${template.template_code} v${template.version} · Base jurídica ${template.legal_basis_version||"legada"} · verificada em ${formatDate(template.legal_reviewed_at)}${template.status==="legal_review_required"?" · revisão profissional recomendada antes da assinatura":""}`:"Modelo indisponível";previewResult=null;stepIndex=Math.min(stepIndex,steps.length-1);refreshConditionalFields();renderStep();}
  const autofillError=reason=>typeof crmFriendlyError==="function"?crmFriendlyError(reason,"Não foi possível reutilizar os dados do CRM."):"Não foi possível reutilizar os dados do CRM.";
  drawFields();typeSelect.addEventListener("change",async()=>{payloadBase={};manualFields=new Set();fieldOrigins={};lastAutofill={};stepIndex=0;drawFields({});try{await refreshAutofill("all");}catch(reason){error.textContent=autofillError(reason);}});
  for(const[name,ref]of Object.entries({property:propertyRef,owner:ownerRef,lead:leadRef,proposal:proposalRef}))ref.select.addEventListener("change",async()=>{referenceManual[name]=true;delete referenceAuto[name];try{await refreshAutofill(name);}catch(reason){error.textContent=autofillError(reason);}});
  prefill.addEventListener("click",async()=>{prefill.disabled=true;error.textContent="";try{await refreshAutofill("all");showToast("Dados disponíveis no CRM atualizados. Seus ajustes manuais foram preservados.");}catch(reason){error.textContent=autofillError(reason);}finally{prefill.disabled=false;}});
  function payload(){return Object.fromEntries(Object.entries(inputs).map(([key,input])=>[key,input.disabled?null:input.dataset.rawValue!==undefined?(input.dataset.rawValue||null):input.value.trim()||null]));}
  headerBack.addEventListener("click",()=>goToStep(stepIndex-1));previous.addEventListener("click",()=>goToStep(stepIndex-1));next.addEventListener("click",()=>goToStep(stepIndex+1));
  body.append(typeLabel,templateInfo,progress,stepCounter,refs,fieldsMount,error);form.append(body,actions);form.addEventListener("submit",async event=>{event.preventDefault();const steps=DOCUMENT_STEPS[typeSelect.value];if(stepIndex!==steps.length-1){goToStep(stepIndex+1);return;}if(preview.disabled)return;preview.disabled=true;error.textContent="";try{const template=currentTemplate();if(!template)throw new Error("Modelo indisponível.");previewResult=await callCrmRpc("preview_real_estate_document",{target_organization:workspace.org,target_template:template.id,target_payload:payload(),target_document:documentRecord?.id||null});await openDocumentPreview({workspace,documentRecord,documentType:typeSelect.value,formPayload:payload(),refs:{property:propertyRef.select.value||null,owner:ownerRef.select.value||null,lead:leadRef.select.value||null,proposal:proposalRef.select.value||null},summary:summary.value,previewResult});}catch(reason){error.textContent=crmFriendlyError(reason,"Não foi possível gerar o preview. Revise os dados e a identidade documental.");}finally{preview.disabled=false;}});
  try{await refreshAutofill("all");}catch(reason){error.textContent=typeof crmFriendlyError==="function"?crmFriendlyError(reason,"Não foi possível carregar o preenchimento automático. Os campos continuam disponíveis para edição manual."):"Não foi possível carregar o preenchimento automático. Os campos continuam disponíveis para edição manual.";}
  card.append(header,intro,form);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");if(window.matchMedia?.("(max-width: 600px)")?.matches)headerClose.focus();else typeSelect.focus();
}

async function openDocumentPreview({workspace,documentRecord,documentType,formPayload,refs,summary,previewResult}){
  const modal=document.getElementById("crmModal"),card=createElement("section",{className:"modal-card document-preview-modal",attrs:{role:"dialog","aria-modal":"true","aria-labelledby":"documentPreviewTitle"}}),missing=previewResult.missing_fields||[],blockers=previewResult.blocking_reasons||[],error=createElement("p",{className:"form-error",attrs:{role:"alert"}});card.append(createElement("h2",{id:"documentPreviewTitle",text:"Revisão e preview"}),createElement("p",{className:"document-basis-line",text:`Base jurídica verificada em ${formatDate(previewResult.legal_reviewed_at)} · ${previewResult.legal_basis_version||"versão legada"}`}));
  if(missing.length){const warning=createElement("div",{className:"document-missing"});warning.append(createElement("strong",{text:"Preenchimento necessário antes de finalizar:"}),createElement("p",{text:missing.map(key=>documentMissingLabel(key,documentType)).join(" · ")}));card.append(warning);}
  if(blockers.length){const warning=createElement("div",{className:"document-blocking"});warning.append(createElement("strong",{text:"Este cenário requer análise jurídica específica:"}));const list=createElement("ul");blockers.forEach(reason=>list.append(createElement("li",{text:reason})));warning.append(list,createElement("p",{text:"Você pode salvar o rascunho ou enviar para revisão, mas não finalizar esta versão."}));card.append(warning);}
  card.append(createDocumentChecklist(previewResult.legal_checklist||[]));
  const identityRow=previewResult.document_identity_id===workspace.identity?.id?workspace.identity:await loadDocumentIdentity(workspace.org,previewResult.document_identity_id),logo=await documentPdfLogo(identityRow),identity=documentIdentitySnapshot(previewResult.identity_snapshot,workspace.organization),logoDataUrl=identityRow?documentLogoDataUrl(identityRow):null;card.append(createDocumentPreviewPages({title:DOCUMENT_TYPE_LABELS[documentType],content:previewResult.content,identity,logo,logoDataUrl,versionLabel:`Preview · Modelo ${previewResult.template_code} v${previewResult.template_version} · Base ${previewResult.legal_basis_version}`,documentIdentifier:"PREVIEW"}),createDocumentNextSteps(documentType));const actions=createElement("div",{className:"modal-actions"}),back=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Voltar e revisar"}),draft=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Salvar rascunho"}),review=createElement("button",{type:"button",className:"crm-button crm-button-outline",text:"Enviar para revisão"}),finalize=createElement("button",{type:"button",className:"crm-button crm-button-primary",text:"Finalizar versão"});finalize.disabled=missing.length>0||blockers.length>0;review.disabled=missing.length>0;
  back.addEventListener("click",async()=>{closeModal();const editableDocument=documentRecord?.id?documentRecord:{document_type:documentType,property_id:refs.property,owner_id:refs.owner,lead_id:refs.lead,proposal_id:refs.proposal};await openDocumentEditor(await loadDocumentWorkspace(),editableDocument,{data_snapshot:formPayload,_summary:summary});});
  async function save(targetStatus){if(draft.disabled)return;[draft,review,finalize,back].forEach(button=>button.disabled=true);error.textContent="";try{const saved=await callCrmRpc("save_real_estate_document_version",{target_organization:workspace.org,target_preview:previewResult.preview_id,target_payload:formPayload,target_document:documentRecord?.id||null,target_property:refs.property,target_owner:refs.owner,target_lead:refs.lead,target_proposal:refs.proposal,target_changes_summary:summary||null});if(targetStatus==="review")await callCrmRpc("submit_real_estate_document_review",{target_organization:workspace.org,target_document:saved.document_id,target_version:saved.version_no});if(targetStatus==="finalized")await callCrmRpc("finalize_real_estate_document",{target_organization:workspace.org,target_document:saved.document_id,target_version:saved.version_no});closeModal();showToast(targetStatus==="finalized"?"Documento finalizado e protegido. Confira os próximos passos para assinatura e formalização.":targetStatus==="review"?"Documento enviado para revisão.":"Rascunho versionado salvo.");await renderCurrentView();}catch(reason){error.textContent=crmFriendlyError(reason,"Não foi possível salvar o documento.");[draft,back].forEach(button=>button.disabled=false);review.disabled=missing.length>0;finalize.disabled=missing.length>0||blockers.length>0;}}
  draft.addEventListener("click",()=>save("draft"));review.addEventListener("click",()=>save("review"));finalize.addEventListener("click",()=>save("finalized"));actions.append(back,draft,review,finalize);card.append(error,actions);modal.replaceChildren(card);modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");back.focus();
}
