function teamRoleLabel(role) { return ({ owner: "Proprietário", manager: "Gerente", agent: "Corretor" })[role] || role; }
function teamStatusLabel(status) { return ({ active: "Ativo", disabled: "Desativado", invited: "Convidado" })[status] || status; }

async function renderTeam(root) {
  const membership = await getActiveMembership();
  if (!["owner", "manager"].includes(membership.role)) { root.replaceChildren(createEmptyState("Acesso restrito", "Sua função não permite gerenciar a equipe.")); return; }
  const [members, invitations] = await Promise.all([getTeamMembers(), getPendingInvitations()]);
  root.replaceChildren();
  const toolbar = createElement("div", { className: "toolbar" });
  toolbar.append(createElement("p", { className: "muted", text: `${members.length} membro(s) cadastrado(s)` }));
  const invite = createElement("button", { className: "crm-button crm-button-primary", text: "+ Convidar", type: "button" }); invite.addEventListener("click", () => openTeamInviteModal(membership.role)); toolbar.append(invite); root.append(toolbar);
  const tableWrap = createElement("div", { className: "lead-table-wrap" }); const table = createElement("table", { className: "lead-table team-table" }); const head = document.createElement("thead"); const header = document.createElement("tr");
  ["Nome", "E-mail", "Função", "Status", "Entrada", "Ações"].forEach(label => header.append(createElement("th", { text: label }))); head.append(header); table.append(head); const body = document.createElement("tbody");
  members.forEach(member => { const row = document.createElement("tr"); row.append(createElement("td", { text: member.full_name || "Sem nome" }), createElement("td", { text: member.email }), createElement("td", { text: teamRoleLabel(member.role) }), createElement("td", { text: teamStatusLabel(member.status) }), createElement("td", { text: formatDate(member.joined_at) })); const actions = createElement("td");
    if (member.can_manage) { const group = createElement("div", { className: "table-actions" }); if (membership.role === "owner") { const role = createElement("select", { className: "filter-select", attrs: { "aria-label": `Função de ${member.full_name}` } }); [["agent", "Corretor"], ["manager", "Gerente"]].forEach(([value, label]) => role.append(new Option(label, value))); role.value = member.role; role.addEventListener("change", () => runTeamAction(() => changeTeamMemberRole(member.user_id, role.value), "Função atualizada.")); group.append(role); }
      const enabled = member.status === "active"; const toggle = createElement("button", { className: "icon-button", text: enabled ? "Desativar" : "Ativar", type: "button" }); toggle.addEventListener("click", () => runTeamAction(() => setTeamMemberEnabled(member.user_id, !enabled), enabled ? "Membro desativado." : "Membro ativado.")); const remove = createElement("button", { className: "icon-button", text: "Remover", type: "button" }); remove.addEventListener("click", () => { if (window.confirm(`Remover ${member.full_name || member.email} da equipe?`)) void runTeamAction(() => removeTeamMember(member.user_id), "Membro removido."); }); group.append(toggle, remove); actions.append(group);
    } else actions.textContent = "—"; row.append(actions); body.append(row); }); table.append(body); tableWrap.append(table); root.append(tableWrap);
  if (invitations.length) { const panel = createElement("section", { className: "crm-panel team-invitations" }); panel.append(createElement("h2", { text: "Convites pendentes" })); invitations.forEach(item => { const line = createElement("div", { className: "lead-row" }); const info = createElement("div"); info.append(createElement("strong", { text: item.email }), createElement("span", { text: `${teamRoleLabel(item.role)} · expira ${formatDate(item.expires_at, true)}` })); const revoke = createElement("button", { className: "icon-button", text: "Revogar", type: "button" }); revoke.addEventListener("click", () => runTeamAction(() => revokeTeamInvitation(item.invitation_id), "Convite revogado.")); line.append(info, revoke); panel.append(line); }); root.append(panel); }
}

function openTeamInviteModal(callerRole) {
  const modal = document.getElementById("crmModal"); const card = createElement("section", { className: "modal-card" }); card.append(createElement("h2", { text: "Convidar para a equipe" })); const form = createElement("form", { className: "crm-form" }); const emailLabel = createElement("label", { text: "E-mail" }); const email = createElement("input", { type: "email", attrs: { required: "", autocomplete: "email" } }); emailLabel.append(email); const roleLabel = createElement("label", { text: "Função" }); const role = createElement("select"); role.append(new Option("Corretor", "agent")); if (callerRole === "owner") role.append(new Option("Gerente", "manager")); roleLabel.append(role); const error = createElement("p", { className: "form-error", attrs: { role: "alert" } }); const actions = createElement("div", { className: "modal-actions" }); const cancel = createElement("button", { className: "crm-button crm-button-outline", text: "Cancelar", type: "button" }); cancel.addEventListener("click", closeModal); const submit = createElement("button", { className: "crm-button crm-button-primary", text: "Gerar convite", type: "submit" }); actions.append(cancel, submit); form.append(emailLabel, roleLabel, error, actions);
  form.addEventListener("submit", async event => { event.preventDefault(); submit.disabled = true; try { const result = await inviteTeamMember(email.value, role.value); const invitation = result?.[0]; const inviteUrl = `${window.location.origin}${window.location.pathname}?invitation=${encodeURIComponent(invitation.invitation_token)}`; const tokenBox = createElement("div", { className: "invite-token" }); tokenBox.append(createElement("strong", { text: "Link exibido uma única vez" }), createElement("code", { text: inviteUrl }), createElement("p", { className: "muted", text: "Envie este link por um canal seguro. O convidado deve entrar com o mesmo e-mail para aceitá-lo." })); form.replaceChildren(tokenBox, actions); submit.remove(); cancel.textContent = "Concluir"; showToast("Convite criado com segurança."); } catch (err) { error.textContent = err.message || "Não foi possível criar o convite."; submit.disabled = false; } }); card.append(form); modal.replaceChildren(card); modal.classList.add("is-open"); modal.setAttribute("aria-hidden", "false");
}

async function runTeamAction(action, successMessage) { try { await action(); showToast(successMessage); await renderCurrentView(); } catch (error) { showToast(error.message || "Ação não concluída.", "error"); } }
