import test from "node:test";import assert from "node:assert/strict";import{readFileSync,existsSync}from"node:fs";import{Script}from"node:vm";
const read=p=>readFileSync(p,"utf8"),crm=read("crm/index.html"),app=read("crm/js/app.js"),data=read("crm/js/premium-data.js"),premium=read("crm/js/premium.js"),properties=read("crm/js/properties.js"),insights=read("crm/js/lead-insights.js"),matching=read("crm/js/crm-advanced-data.js"),css=read("crm/css/premium.css"),migration=read("supabase/migrations/20260913000000_private_beta_premium.sql"),catalog=read("js/public-catalog.js"),index=read("index.html"),detail=read("js/imovel.js"),sw=read("crm/service-worker.js"),seed=read("scripts/build-catalog-seed.mjs");
test("P01 premium views are reachable",()=>["matching","proposals","reports","assistant","notifications","site-status","settings"].forEach(v=>assert.match(app,new RegExp(`${v.replace('-','\\-')}`))));
test("P02 global quick create exposes real actions",()=>["Novo lead","Novo imóvel","Agendar visita","Criar follow-up","Criar tarefa","Registrar proposta"].forEach(x=>assert.match(premium,new RegExp(x))));
test("P03 lead 360 uses audited history and insights",()=>{assert.match(premium,/openKanbanDetail/);assert.match(insights,/O que o cliente procura/);assert.match(insights,/Imóveis de interesse/)});
test("P04 structured preferences are persisted",()=>["preference_purpose","preference_max_area","preference_min_suites","preference_min_bathrooms","preference_min_parking","preference_features"].forEach(x=>assert.match(migration,new RegExp(x))));
test("P05 matching stays deterministic and explains divergences",()=>{assert.match(matching,/compatibility/);assert.match(matching,/divergences/);assert.doesNotMatch(matching,/openai|anthropic|gemini/i)});
test("P06 dashboard metrics are actionable",()=>assert.match(read("crm/js/dashboard.js"),/metric-action[\s\S]*navigateCrm/));
test("P07 origin labels are friendly",()=>assert.match(premium,/manual:"Cadastro manual"/));
test("P08 property management is integrated",()=>["saveManagedProperty","replacePropertyMedia","uploadPropertyPhoto"].forEach(x=>assert.match(properties+data,new RegExp(x))));
test("P09 property workflow has publication statuses",()=>["Rascunho","Disponível","Reservado","Vendido","Inativo"].forEach(x=>assert.match(properties,new RegExp(x))));
test("P10 mobile photo workflow keeps order and cover atomically",()=>{assert.match(properties,/A primeira foto é a capa/);assert.match(data,/replace_property_media/);assert.match(migration,/item_index=0/);assert.doesNotMatch(data,/canvas|compress|resize/i)});
test("P11 public catalog uses safe RPC with fallback",()=>{assert.match(catalog,/list_public_properties/);assert.match(catalog,/fallbackPath/);assert.match(index,/loadPublishedProperties/);assert.match(detail,/loadPublishedProperties/)});
test("P12 public RPC exposes published properties only",()=>assert.match(migration,/p\.is_published and p\.status in \('available','reserved'\)/));
test("P13 private property tables force RLS",()=>["properties","property_media","proposals","crm_notifications"].forEach(t=>assert.match(migration,new RegExp(`alter table public\\.${t} force row level security`))));
test("P14 proposals are commercial records",()=>{assert.match(migration,/create table public\.proposals/);assert.match(premium,/sem confundi-las com contrato jurídico/)});
test("P15 commission visibility follows lead access",()=>assert.match(migration,/premium_proposals_select[\s\S]*can_access_lead/));
test("P16 notifications are deduplicated and actionable",()=>{assert.match(migration,/unique\(user_id,dedupe_key\)/);assert.match(premium,/markNotificationRead/)});
test("P17 search runs in a tenant-scoped RPC",()=>{assert.match(migration,/crm_global_search/);assert.match(migration,/organization_id=target_organization/)});
test("P18 assistant uses backend facts without fake AI",()=>{assert.match(migration,/get_assistant_briefing/);assert.match(premium,/Nenhum modelo generativo ou dado fictício/)});
test("P19 site status reports verified backend signals",()=>{assert.match(migration,/get_site_status/);assert.match(premium,/Não verificado/);assert.doesNotMatch(premium,/Site online/)});
test("P20 profile can repair missing member name",()=>{assert.match(premium,/Perfil profissional/);assert.match(data,/updateMyProfile/)});
test("P21 phone and BRL helpers are centralized",()=>{const u=read("crm/js/utils.js");assert.match(u,/function formatPhone/);assert.match(u,/function parseBrlNumber/)});
test("P22 mobile viewport is clipped except intentional Kanban",()=>{assert.match(css,/overflow-x:clip/);assert.match(css,/\.kanban-view,\.kanban\{contain:none/)});
test("P23 touch and reduced motion remain supported",()=>{assert.match(css,/min-width:44px/);assert.match(css,/prefers-reduced-motion/)});
test("P24 PWA cache version includes premium CSS",()=>{assert.match(sw,/shell-premium/);assert.match(sw,/premium\.css/);assert.doesNotMatch(sw,/rest\/v1|auth\/v1/)});
test("P25 storage upload accepts only public image types and 15MB",()=>{assert.match(migration,/image\/jpeg/);assert.match(data,/15 \* 1024 \* 1024/)});
test("P26 catalog seed preserves expected codes",async()=>{const source=JSON.parse(read("data/imoveis.json"));assert.deepEqual(source.filter(x=>x.ativo).map(x=>x.codigo),["VCI000002","VCI000003","VCI000004","VCI000005","VCI000006"]);assert.match(seed,/VCI000001/)});
test("P27 VCI000004 and VCI000006 media are untouched",()=>{const source=JSON.parse(read("data/imoveis.json"));assert.equal(source.find(x=>x.codigo==="VCI000004").imagens.length,7);const six=source.find(x=>x.codigo==="VCI000006");assert.equal(six.imagens.length,6);assert.match(six.imagens[0],/01-area-externa-piscinas/)});
test("P28 no legal-document generator or automatic messaging was introduced",()=>[premium,data,properties,migration].forEach(x=>assert.doesNotMatch(x,/gerar contrato|send whatsapp|send email/i)));
test("P29 Capacitor and store billing remain untouched",()=>{assert.ok(existsSync("capacitor.config.json"));assert.doesNotMatch(crm,/StoreKit|BillingClient/)});
test("P30 new client code contains no secret-shaped value",()=>[premium,data,properties,catalog,css].forEach(x=>assert.doesNotMatch(x,/service_role|RESEND_API_KEY|sk_live_|eyJ[A-Za-z0-9_-]{20,}/)));
test("P31 scripts parse",()=>["crm/js/premium-data.js","crm/js/properties.js","crm/js/premium.js","js/public-catalog.js"].forEach(path=>assert.doesNotThrow(()=>new Script(read(path)))));
