import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync,readdirSync} from "node:fs";
import {PGlite} from "@electric-sql/pglite";
import {pgcrypto} from "@electric-sql/pglite/contrib/pgcrypto";

const db=new PGlite({extensions:{pgcrypto}});
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create schema extensions; create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}'); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema public,auth to anon,authenticated,service_role; create extension pgcrypto with schema extensions;`);
for(const file of readdirSync("supabase/migrations").filter(name=>name.endsWith(".sql")).sort())await db.exec(readFileSync(`supabase/migrations/${file}`,"utf8"));

const ids={owner:"67000000-0000-0000-0000-000000000001",manager:"67000000-0000-0000-0000-000000000002",agent:"67000000-0000-0000-0000-000000000003",other:"67000000-0000-0000-0000-000000000004"};
for(const[name,id]of Object.entries(ids))await db.query("insert into auth.users(id,email,raw_user_meta_data) values($1,$2,'{\"public_signup\":false,\"full_name\":\"Usuário Teste\"}')",[id,`${name}@documents.invalid`]);
const org=(await db.query("select organization_id from profiles where id=$1",[ids.owner])).rows[0].organization_id,otherOrg=(await db.query("select organization_id from profiles where id=$1",[ids.other])).rows[0].organization_id;
await db.query("update subscriptions set plan_id=(select id from plans where code='pro'),status='active',current_period_ends_at=now()+interval '30 days' where organization_id=$1 and is_current",[org]);
await db.query("insert into organization_members(organization_id,user_id,role,status) values($1,$2,'manager','active'),($1,$3,'agent','active')",[org,ids.manager,ids.agent]);
await db.query("update profiles set full_name='Corretor Teste',creci='CRECI 1234',phone='65999990000' where id=$1",[ids.owner]);
const property=(await db.query("insert into properties(organization_id,code,title,slug,price,city,state,status,created_by) values($1,'VCI999991','Imóvel de teste','imovel-teste',550000,'Cuiabá','MT','draft',$2) returning id",[org,ids.owner])).rows[0];
const ownerRow=(await db.query("insert into property_owners(organization_id,full_name,phone,assigned_to,created_by) values($1,'Vendedor Teste','65999990001',$2,$2) returning id",[org,ids.owner])).rows[0];
const lead=(await db.query("insert into leads(organization_id,assigned_to,name,phone) values($1,$2,'Comprador Teste','65999990002') returning id",[org,ids.agent])).rows[0];
const otherLead=(await db.query("insert into leads(organization_id,assigned_to,name,phone) values($1,$2,'Lead de outro tenant','65999990003') returning id",[otherOrg,ids.other])).rows[0];
async function as(who,sql,args=[]){await db.exec("reset role");if(who)await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[who]]);else await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec(`set role ${who?"authenticated":"anon"}`);try{return await db.query(sql,args);}finally{await db.exec("reset role");}}
const denied=(who,sql,args=[])=>assert.rejects(as(who,sql,args),error=>["42501","22023"].includes(error.code));
const template=async type=>(await as("owner","select id from document_templates where document_type=$1 order by version desc limit 1",[type])).rows[0].id;
const completeIntermediation={seller_name:"Vendedor Teste",seller_contact:"(65) 99999-0001",broker_name:"Corretor Teste",broker_creci:"CRECI 1234",broker_contact:"(65) 99999-0000",property_description:"VCI999991, Imóvel de teste, Cuiabá/MT",registry_information:null,offer_price:"R$ 550.000,00",commercial_conditions:"Pagamento conforme proposta aceita pelas partes.",remuneration_terms:"Remuneração fixa expressamente acordada em R$ 10.000,00.",term_text:"90 dias a partir da assinatura.",exclusivity:"non_exclusive",publicity_authorization:"Divulgação autorizada no site e portais cadastrados, sem dados privados.",closing_terms:"Encerramento por termo escrito ou término do prazo, observadas as obrigações já constituídas.",city:"Cuiabá/MT",document_date:"2026-09-17"};
const completePurchase={seller_name:"Vendedor Teste",seller_contact:"(65) 99999-0001",buyer_name:"Comprador Teste",buyer_contact:"(65) 99999-0002",property_description:"VCI999991, Imóvel de teste, Cuiabá/MT",registry_information:null,price:"R$ 550.000,00",payment_terms:"Pagamento nas condições expressamente aceitas pelas partes.",arras_option:"none",arras_terms:null,financing_option:"none",financing_terms:null,possession_terms:"Posse na data expressamente acordada após a quitação.",deed_transfer_terms:"Escritura e transferência conforme requisitos legais e datas acordadas.",taxes_expenses_terms:"Responsabilidades serão as expressamente descritas nesta minuta revisada.",debts_terms:"Nenhum débito foi informado para esta validação sintética.",brokerage_terms:"Corretagem conforme instrumento de intermediação separado.",default_terms:"Consequências dependem do ajuste expresso e da revisão jurídica.",termination_terms:"Rescisão conforme hipóteses expressamente acordadas e legislação aplicável.",city:"Cuiabá/MT",document_date:"2026-09-17",witnesses:null};

test("DOCDB01 templates are readable but not client-mutable",async()=>{assert.equal((await as("owner","select count(*)::int n from document_templates")).rows[0].n,2);await assert.rejects(as("owner","update document_templates set name='Alterado'"),error=>error.code==="42501");});

test("DOCDB02 prefill is tenant safe and does not invent registration",async()=>{const value=(await as("owner","select get_real_estate_document_prefill($1,'sale_intermediation',$2,$3,$4,null) value",[org,property.id,ownerRow.id,lead.id])).rows[0].value;assert.equal(value.seller_name,"Vendedor Teste");assert.equal(value.buyer_name,"Comprador Teste");assert.equal(value.broker_creci,"CRECI 1234");assert.equal(value.registry_information,undefined);await denied("owner","select get_real_estate_document_prefill($1,'property_sale_purchase',null,null,$2,null)",[org,otherLead.id]);});

test("DOCDB03 preview is mandatory, hash-bound and finalization blocks incomplete data",async()=>{const templateId=await template("sale_intermediation"),incomplete={...completeIntermediation,broker_creci:null};const preview=(await as("owner","select preview_real_estate_document($1,$2,$3::jsonb,null) value",[org,templateId,JSON.stringify(incomplete)])).rows[0].value;assert.ok(preview.missing_fields.includes("broker_creci"));const saved=(await as("owner","select save_real_estate_document_version($1,$2,$3::jsonb,null,$4,$5,$6,null,null) value",[org,preview.preview_id,JSON.stringify(incomplete),property.id,ownerRow.id,lead.id])).rows[0].value;await assert.rejects(as("owner","select finalize_real_estate_document($1,$2,$3)",[org,saved.document_id,saved.version_no]),error=>error.code==="22023");await denied("other","select * from real_estate_documents where organization_id=$1",[org]);});

test("DOCDB04 final versions are immutable and later changes create a new version",async()=>{const templateId=await template("sale_intermediation"),preview=(await as("owner","select preview_real_estate_document($1,$2,$3::jsonb,null) value",[org,templateId,JSON.stringify(completeIntermediation)])).rows[0].value,saved=(await as("owner","select save_real_estate_document_version($1,$2,$3::jsonb,null,$4,$5,$6,null,'Primeira minuta') value",[org,preview.preview_id,JSON.stringify(completeIntermediation),property.id,ownerRow.id,lead.id])).rows[0].value;await as("owner","select submit_real_estate_document_review($1,$2,$3)",[org,saved.document_id,saved.version_no]);await as("owner","select finalize_real_estate_document($1,$2,$3)",[org,saved.document_id,saved.version_no]);await assert.rejects(as("owner","update real_estate_document_versions set rendered_content='alterado' where document_id=$1",[saved.document_id]),error=>error.code==="42501");const changed={...completeIntermediation,term_text:"120 dias a partir da assinatura."},preview2=(await as("owner","select preview_real_estate_document($1,$2,$3::jsonb,$4) value",[org,templateId,JSON.stringify(changed),saved.document_id])).rows[0].value,saved2=(await as("owner","select save_real_estate_document_version($1,$2,$3::jsonb,$4,$5,$6,$7,null,'Prazo revisto') value",[org,preview2.preview_id,JSON.stringify(changed),saved.document_id,property.id,ownerRow.id,lead.id])).rows[0].value;assert.equal(saved2.version_no,2);assert.equal((await as("owner","select count(*)::int n from real_estate_document_versions where document_id=$1",[saved.document_id])).rows[0].n,2);});

test("DOCDB05 agent access follows portfolio and cross-tenant references fail",async()=>{const templateId=await template("sale_intermediation"),preview=(await as("agent","select preview_real_estate_document($1,$2,$3::jsonb,null) value",[org,templateId,JSON.stringify(completeIntermediation)])).rows[0].value;const saved=(await as("agent","select save_real_estate_document_version($1,$2,$3::jsonb,null,$4,null,$5,null,null) value",[org,preview.preview_id,JSON.stringify(completeIntermediation),property.id,lead.id])).rows[0].value;assert.equal((await as("agent","select count(*)::int n from real_estate_documents where id=$1",[saved.document_id])).rows[0].n,1);await denied("agent","select get_real_estate_document_prefill($1,'property_sale_purchase',null,null,$2,null)",[org,otherLead.id]);await denied(null,"select preview_real_estate_document($1,$2,$3::jsonb,null)",[org,templateId,JSON.stringify(completeIntermediation)]);});

test("DOCDB06 purchase contract requires explicit legal decisions and valid date",async()=>{const templateId=await template("property_sale_purchase"),preview=(await as("owner","select preview_real_estate_document($1,$2,$3::jsonb,null) value",[org,templateId,JSON.stringify(completePurchase)])).rows[0].value;assert.deepEqual(preview.missing_fields,[]);assert.match(preview.content,/não há sinal\/arras/);assert.match(preview.content,/17\/09\/2026/);const missingTerms=(await as("owner","select preview_real_estate_document($1,$2,$3::jsonb,null) value",[org,templateId,JSON.stringify({...completePurchase,arras_option:"applicable"})])).rows[0].value;assert.ok(missingTerms.missing_fields.includes("arras_terms"));await assert.rejects(as("owner","select preview_real_estate_document($1,$2,$3::jsonb,null)",[org,templateId,JSON.stringify({...completePurchase,document_date:"17/09/2026"})]),error=>error.code==="22023");});

test("DOCDB07 PDF audit and cancellation retain content without personal text in logs",async()=>{const row=(await as("owner","select d.id,v.version_no from real_estate_documents d join real_estate_document_versions v on v.document_id=d.id where v.status='finalized' limit 1")).rows[0];assert.ok(row);assert.equal((await as("owner","select record_real_estate_document_pdf($1,$2,$3) value",[org,row.id,row.version_no])).rows[0].value,true);await as("owner","select cancel_real_estate_document($1,$2)",[org,row.id]);const audit=(await db.query("select metadata from audit_events where entity_id=$1 and action='document_pdf_generated'",[row.id])).rows[0].metadata;assert.equal(audit.version,row.version_no);assert.equal(JSON.stringify(audit).includes("Vendedor Teste"),false);assert.equal((await db.query("select count(*)::int n from real_estate_document_versions where document_id=$1",[row.id])).rows[0].n,2);});

test.after(async()=>db.close());
