import {serve} from "https://deno.land/std@0.224.0/http/server.ts";
import {createClient} from "https://esm.sh/@supabase/supabase-js@2";
import {generatePropertyAdPdf} from "../_shared/property-ad-pdf.ts";
const MAX_BODY=15000;const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const TIMES=new Set(["Manhã","Tarde","Noite"]);
const clean=(v:unknown,n:number)=>String(v??"").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,n);
const cors=(origin:string|null)=>{const allowed=(Deno.env.get("SELL_PROPERTY_ALLOWED_ORIGINS")||"").split(",").map(x=>x.trim().replace(/\/$/,"")).filter(Boolean);const normalized=origin?.replace(/\/$/,"")||"";return normalized&&allowed.includes(normalized)?{"Access-Control-Allow-Origin":normalized,"Access-Control-Allow-Headers":"apikey, authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin"}:null};
const reply=(body:Record<string,unknown>,status:number,headers:Record<string,string>)=>new Response(JSON.stringify(body),{status,headers:{...headers,"Content-Type":"application/json; charset=utf-8"}});
const b64=(bytes:Uint8Array)=>{let binary="";for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(binary)};
const escapeHtml=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
async function rateKey(request:Request){const salt=Deno.env.get("SELL_PROPERTY_RATE_LIMIT_SALT");if(!salt)throw new Error("Rate limit not configured");const ip=(request.headers.get("x-forwarded-for")||"unknown").split(",")[0].trim().slice(0,128);const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(`${ip}:${salt}:property-ad`));return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function sendEmail(payload:Record<string,unknown>,requestId:string){const mode=Deno.env.get("SELL_PROPERTY_EMAIL_MODE")||"disabled";if(mode==="mock"){if(Deno.env.get("SELL_PROPERTY_ALLOW_MOCK")!=="true")throw new Error("Mock transport is disabled");const url=Deno.env.get("SELL_PROPERTY_EMAIL_MOCK_URL");if(!url)throw new Error("Mock transport not configured");const response=await fetch(`${url.replace(/\/$/,"")}/send`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`Mock transport HTTP ${response.status}`);return}
 if(mode!=="resend")throw new Error("Email provider not configured");const key=Deno.env.get("RESEND_API_KEY");if(!key)throw new Error("Email provider not configured");const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","Idempotency-Key":`property-ad/${requestId}`},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`Email transport HTTP ${response.status}`)}
serve(async request=>{const headers=cors(request.headers.get("origin"));if(!headers)return new Response(null,{status:403});if(request.method==="OPTIONS")return new Response(null,{status:204,headers});if(request.method!=="POST")return reply({error:"Método não permitido."},405,headers);if(Number(request.headers.get("content-length")||0)>MAX_BODY)return reply({error:"Solicitação inválida."},413,headers);
 let raw;try{const body=await request.text();if(new TextEncoder().encode(body).length>MAX_BODY)return reply({error:"Solicitação inválida."},413,headers);raw=JSON.parse(body)}catch{return reply({error:"Solicitação inválida."},400,headers)}if(!raw||Array.isArray(raw)||typeof raw!=="object")return reply({error:"Solicitação inválida."},400,headers);if(clean(raw.website,120))return reply({ok:true},200,headers);
 const data={requestId:clean(raw.requestId,36),name:clean(raw.name,120),phone:clean(raw.phone,24).replace(/\D/g,""),propertyType:clean(raw.propertyType,60),location:clean(raw.location,160),approximateValue:clean(raw.approximateValue,80),description:clean(raw.description,800),preferredTime:clean(raw.preferredTime,20)};
 if(!UUID.test(data.requestId)||data.name.length<2||data.phone.length<8||data.phone.length>15||data.propertyType.length<2||data.location.length<2||!TIMES.has(data.preferredTime))return reply({error:"Confira os dados informados."},422,headers);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),org=Deno.env.get("SELL_PROPERTY_ORGANIZATION_ID"),recipient=Deno.env.get("SELL_PROPERTY_RECIPIENT_EMAIL"),from=Deno.env.get("SELL_PROPERTY_FROM_EMAIL");if(!url||!key||!org)return reply({error:"Serviço indisponível."},503,headers);const admin=createClient(url,key,{auth:{persistSession:false}});
 const max=Math.min(Math.max(Number(Deno.env.get("SELL_PROPERTY_RATE_LIMIT_MAX")||5),1),20);const {data:allowed,error:rateError}=await admin.rpc("consume_site_lead_rate_limit",{target_key:await rateKey(request),max_requests:max,window_seconds:3600});if(rateError||!allowed)return reply({error:"Tente novamente mais tarde."},429,headers);
 const {data:captured,error:captureError}=await admin.rpc("capture_property_ad_request",{target_organization:org,target_request_id:data.requestId,target_name:data.name,target_phone:data.phone,target_property_type:data.propertyType,target_location:data.location,target_approximate_value:data.approximateValue,target_description:data.description,target_preferred_time:data.preferredTime});if(captureError||!captured?.[0]?.request_id)return reply({error:"Não foi possível registrar sua solicitação."},503,headers);const row=captured[0];let emailStatus=row.email_status;
 const {data:claimed}=await admin.rpc("claim_property_ad_email",{target_request_id:data.requestId,target_organization:org});if(claimed){const submittedAt=new Date(),pdf=generatePropertyAdPdf({...data,submittedAt});try{if(!recipient||!from)throw new Error("Email recipient/from not configured");const when=new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Cuiaba"}).format(submittedAt);const fields=[["Nome",data.name],["Telefone / WhatsApp",data.phone],["Tipo de imóvel",data.propertyType],["Localização",data.location],["Valor aproximado",data.approximateValue||"Não informado"],["Descrição",data.description||"Não informada"],["Horário preferido",data.preferredTime],["Data/hora",when],["Origem","anunciar_imovel"],["Identificador",data.requestId]];await sendEmail({from,to:[recipient],subject:"Nova solicitação para anunciar imóvel",html:`<h1>Nova solicitação para anunciar imóvel</h1>${fields.map(([a,b])=>`<p><strong>${escapeHtml(a)}:</strong> ${escapeHtml(b)}</p>`).join("")}`,attachments:[{filename:`solicitacao-anunciar-imovel-${data.requestId}.pdf`,content:b64(pdf)}]},data.requestId);const {error:completeError}=await admin.rpc("complete_property_ad_email",{target_request_id:data.requestId,target_organization:org,succeeded:true,error_message:null,target_pdf_size:pdf.length});if(completeError)throw new Error("Email status could not be completed");emailStatus="sent"}catch(error){const {error:failError}=await admin.rpc("complete_property_ad_email",{target_request_id:data.requestId,target_organization:org,succeeded:false,error_message:error instanceof Error?error.message:"Falha no transporte",target_pdf_size:pdf.length});emailStatus=failError?"sending":"failed"}}
 return reply({ok:true,requestId:data.requestId,leadId:row.lead_id,emailStatus},row.created?201:200,headers)});
