import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';

const read = path => readFileSync(path, 'utf8');
const migration = read('supabase/migrations/20260912000000_phase_i_public_saas.sql');
const signup = read('crm/signup.html');
const signupJs = read('crm/js/signup.js');
const supabaseJs = read('crm/js/supabase.js');
const billing = read('crm/js/billing.js');
const subscriptions = read('crm/js/subscriptions.js');
const app = read('crm/js/app.js');
const data = read('crm/js/data.js');
const edge = read('supabase/functions/billing-provider-event/index.ts');
const docs = read('docs/phase-i.md');

test('public signup page exists and is pt-BR', () => assert.match(signup, /lang="pt-BR"/));
test('signup requires full name', () => assert.match(signup, /name="fullName"[^>]*required/));
test('signup requires valid email input', () => assert.match(signup, /type="email"[^>]*required/));
test('signup requires telephone with mobile input mode', () => assert.match(signup, /type="tel"[^>]*inputmode="tel"[^>]*required/));
test('signup requires password without manually storing it', () => { assert.match(signup, /autocomplete="new-password"[^>]*required minlength="8"/); assert.doesNotMatch(migration, /password\s+(?:text|varchar)/i); });
test('CRECI is optional', () => assert.match(signup, /name="creci"[^>]*maxlength/));
test('company name is optional', () => assert.match(signup, /name="companyName"[^>]*maxlength/));
test('legal consent is required and not prechecked', () => { const checkbox = signup.match(/<input type="checkbox"[^>]+>/)?.[0] || ''; assert.match(checkbox, /required/); assert.doesNotMatch(checkbox, /checked/); });
test('signup links terms and privacy', () => { assert.match(signup, /termos\.html/); assert.match(signup, /privacidade\.html/); });
test('frontend validates email phone and password', () => { assert.match(signupJs, /emailPattern/); assert.match(signupJs, /phoneDigits/); assert.match(signupJs, /password\.length < 8/); });
test('Supabase Auth receives password directly over signup API', () => { assert.match(supabaseJs, /auth\/v1\/signup/); assert.match(supabaseJs, /password: payload\.password/); });
test('signup fails closed until backend capability is deployed', () => { assert.match(supabaseJs, /public_signup_available/); assert.match(supabaseJs, /aguardando uma atualização segura/); });
test('organization id is never accepted from public signup payload', () => assert.doesNotMatch(supabaseJs.match(/async function signUpPublicAccount[\s\S]+?\n}/)?.[0] || '', /organization_id/));
test('backend creates owner and organization in auth trigger', () => { assert.match(migration, /insert into public\.organizations/); assert.match(migration, /values\(new_org_id,new\.id,'owner','active'\)/); });
test('public signup metadata is validated by backend', () => assert.match(migration, /Cadastro publico incompleto/));
test('trial is exactly seven days using database timestamps', () => { assert.match(migration, /trial_end timestamptz := now\(\) \+ interval '7 days'/); assert.match(migration, /ends_at = started_at \+ interval '7 days'/); });
test('trial cannot repeat for same user', () => assert.match(migration, /unique \(user_id\)/));
test('trial cannot repeat for same organization', () => assert.match(migration, /unique \(organization_id\)/));
test('all catalog plans use seven trial days', () => assert.match(migration, /set trial_days = 7/));
test('demo billing catalog mirrors the exact seven-day production trial', () => { const trialValues = [...data.matchAll(/trial_days:\s*(\d+)/g)].map(match => Number(match[1])); assert.deepEqual(trialValues, [7,7,7]); });
test('monthly prices remain START 3990 PRO 7990 EQUIPE 14990', () => { const plans = read('supabase/migrations/20260825200000_plans_entitlements.sql'); for (const value of ['3990','7990','14990']) assert.match(plans, new RegExp(value)); });
test('annual prices are 39900 79900 and 149900 cents', () => { for (const value of ['39900','79900','149900']) assert.match(migration, new RegExp(value)); });
test('team entitlement remains limited to 30', () => assert.match(read('supabase/migrations/20260825200000_plans_entitlements.sql'), /'equipe','team\.members',true,30/));
test('canceled subscription remains entitled only before period end', () => assert.match(migration, /when 'canceled' then subscription\.current_period_ends_at is not null and subscription\.current_period_ends_at > at_time/));
test('expired refunded and revoked fail entitlement closed', () => { assert.match(migration, /'refunded','revoked'/); assert.doesNotMatch(migration.match(/create or replace function public\.subscription_is_entitled[\s\S]+?\$\$;/)?.[0] || '', /when '(?:expired|refunded|revoked)' then true/); });
test('commercial access is enforced by backend helpers', () => { for (const name of ['can_operate_organization','can_access_lead','is_assignable_member']) assert.match(migration, new RegExp(`function public\\.${name}[\\s\\S]+?organization_has_commercial_access`)); });
test('account and billing membership remains available after expiry', () => assert.match(migration, /membership_role_for_account/));
test('billing tables remain denied to authenticated clients', () => assert.match(read('supabase/migrations/20260827000000_phase_e_billing.sql'), /revoke all on table public\.plans,public\.plan_entitlements,public\.subscriptions/));
test('verified event RPC is service-role only', () => { assert.match(migration, /apply_verified_billing_event[\s\S]+to service_role/); assert.match(migration, /from public,anon,authenticated/); });
test('provider events are idempotent', () => { assert.match(migration, /on conflict\(provider,external_event_id\) do nothing/); assert.match(migration, /'duplicate'/); });
test('out-of-order provider events are ignored', () => assert.match(migration, /ignored_out_of_order/));
test('provider event ingress is disabled by default and no-store', () => { assert.match(edge, /BILLING_PROVIDER_EVENTS_ENABLED/); assert.match(edge, /Cache-Control.*no-store/); assert.match(edge, /503/); });
test('provider ingress performs constant-time secret comparison', () => assert.match(edge, /safeEqual/));
test('client adapters never grant entitlement', () => { assert.match(subscriptions, /configured: false/); assert.doesNotMatch(subscriptions, /apply_verified_billing_event|service_role/); });
test('billing supports monthly and annual UI', () => { assert.match(billing, /Mensal/); assert.match(billing, /Anual/); assert.match(billing, /2 meses grátis no anual/); });
test('restore purchases is present and fails safely before configuration', () => { assert.match(billing, /Restaurar compras/); assert.match(subscriptions, /Nenhum acesso foi concedido sem validação/); });
test('expired UI restricts commercial navigation without deleting data', () => { assert.match(app, /is-restricted/); assert.match(app, /quickLeadButton/); assert.doesNotMatch(app, /deleteLead|DELETE/); });
test('agent and manager deletion requests revoke membership without deleting commercial data', () => { assert.match(migration, /role_value in \('agent','manager'\)/); assert.match(migration, /set status='disabled'/); assert.doesNotMatch(migration.match(/request_account_deletion[\s\S]+?end \$\$/)?.[0] || '', /delete from public\.(?:leads|organizations)/); });
test('single owner deletion is review-only', () => { assert.match(migration, /owner_count=1 then 'organization'/); assert.match(migration, /pending_review/); });
test('public deletion privacy and terms pages exist', () => { for (const file of ['crm/exclusao-de-conta.html','crm/privacidade.html','crm/termos.html']) assert.equal(existsSync(file), true); });
test('consent versions are stored server-side', () => { assert.match(migration, /account_consents/); assert.match(supabaseJs, /terms_version: "2026-09-12"/); });
test('PWA service worker remains private-data safe', () => { const sw = read('crm/service-worker.js'); assert.match(sw, /url\.origin !== self\.location\.origin/); assert.match(sw, /css\|js\|png\|svg\|ico\|webmanifest/); assert.doesNotMatch(sw, /supabase|\/rest\/v1|\/auth\/v1/); });
test('phase documentation identifies store work as pending rather than simulated', () => { assert.match(docs, /não criada/i); assert.match(docs, /não habilitar/i); assert.match(docs, /12 testadores/); assert.match(docs, /14 dias/); });
test('no frontend service role secret is introduced', () => { for (const source of [signupJs,supabaseJs,billing,subscriptions,app]) assert.doesNotMatch(source, /service[_-]?role/i); });
